from nsetools import Nse
nse = Nse()
import streamlit as st
import numpy as np
import yfinance as yf
import random
from pypfopt import DiscreteAllocation
from pypfopt import HRPOpt
from pypfopt import EfficientFrontier
from pypfopt import risk_models, expected_returns
from pypfopt import objective_functions
from pypfopt import EfficientCVaR
from pypfopt import CLA
import itertools
from PIL import Image



def price():
    
    lc =  ['TORNTPOWER.NS', 'IGL.NS', 'ATGL.NS', 'GAIL.NS', 'ADANIPOWER.NS', 'TATAPOWER.NS', 'NHPC.NS', 'ADANIGREEN.NS', 'GUJGASLTD.NS', 'ADANITRANS.NS', 'POWERGRID.NS', 'NTPC.NS', 'LTTS.NS', 'VAKRANGEE.NS', 'MASTEK.NS', 'WIPRO.NS', 'KPITTECH.NS', 'LTI.NS', 'WHIRLPOOL.NS', 'MINDTREE.NS', 'ZENSARTECH.NS', 'BSOFT.NS', 'AMBER.NS', 'IFBIND.NS', 'SONATSOFTW.NS', 'POWERINDIA.NS', 'JCHAC.NS', 'PERSISTENT.NS', 'HCLTECH.NS', 'STLTECH.NS', 'SUBEXLTD.NS', 'HAPPSTMNDS.NS', 'AGCNET.NS', 'FSL.NS', 'INFIBEAM.NS', 'ECLERX.NS', 'INTELLECT.NS', 'ITI.NS', 'HFCL.NS', 'REDINGTON.NS', 'DIXON.NS', 'INFY.NS', 'NEWGEN.NS', 'TCS.NS', 'TECHM.NS', 'COFORGE.NS', 'MPHASIS.NS', 'TATAELXSI.NS', 'SWSOLAR.NS', 'TANLA.NS', 'OFSS.NS', 'LODHA.NS',  'GODREJPROP.NS',  'DLF.NS', '3MINDIA.NS', 'ABB.NS', 'HONAUT.NS', 'VOLTAS.NS', 'CONCOR.NS', 'INDIGO.NS', 'CUMMINSIND.NS', 'SIEMENS.NS', 'ADANIPORTS.NS', 'ASTRAL.NS', 'BHEL.NS', 'LT.NS', 'HAL.NS', 'HAVELLS.NS', 'POLYCAB.NS', 'BEL.NS', 'IRCTC.NS', 'SUNPHARMA.NS', 'DRREDDY.NS', 'APOLLOHOSP.NS', 'DIVISLAB.NS', 'BIOCON.NS', 'PFIZER.NS', 'ALKEM.NS', 'IPCALAB.NS', 'GLAXO.NS', 'GLAND.NS', 'CIPLA.NS', 'TORNTPHARM.NS', 'LUPIN.NS', 'MAXHEALTH.NS', 'ABBOTINDIA.NS', 'AUROPHARMA.NS', 'LALPATHLAB.NS', 'LAURUSLABS.NS', 'CADILAHC.NS', 'SYNGENE.NS', 'BAJFINANCE.NS', 'SUNDARMFIN.NS', 'PNB.NS', 'IDBI.NS', 'HDFCLIFE.NS', 'MFSL.NS', 'CHOLAFIN.NS', 'IDFCFIRSTB.NS', 'BAJAJHLDNG.NS', 'GICRE.NS', 'PFC.NS', 'PEL.NS', 'SRTRANSFIN.NS', 'NIACL.NS', 'MUTHOOTFIN.NS', 'HDFCBANK.NS', 'HDFCAMC.NS', 'NAM-INDIA.NS', 'HDFC.NS', 'BANDHANBNK.NS', 'UNIONBANK.NS', 'BANKBARODA.NS', 'RECLTD.NS', 'AUBANK.NS', 'IRFC.NS', 'L&TFH.NS', 'BANKINDIA.NS', 'CANBK.NS', 'KOTAKBANK.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SBIN.NS', 'LICHSGFIN.NS', 'ICICIPRULI.NS', 'INDUSINDBK.NS', 'BAJAJFINSV.NS', 'IOB.NS', 'ICICIGI.NS', 'ICICIBANK.NS', 'YESBANK.NS', 'AXISBANK.NS', 'ABCAPITAL.NS', 'ADANIENT.NS', 'ONGC.NS', 'PETRONET.NS', 'RELIANCE.NS', 'COALINDIA.NS', 'BPCL.NS', 'HINDPETRO.NS', 'IOC.NS', 'MCDOWELL-N.NS', 'PGHH.NS', 'NESTLEIND.NS', 'GODREJCP.NS', 'MARICO.NS', 'RUCHI.NS', 'DABUR.NS', 'TATACONSUM.NS', 'COLPAL.NS', 'BRITANNIA.NS', 'VBL.NS', 'UBL.NS', 'EMAMILTD.NS', 'DMART.NS', 'ITC.NS', 'HINDUNILVR.NS', 'MARUTI.NS', 'M&M.NS', 'TVSMOTOR.NS', 'MRF.NS', 'MOTHERSUMI.NS', 'ASHOKLEY.NS', 'BAJAJ-AUTO.NS', 'JUBLFOOD.NS', 'BALKRISIND.NS', 'RELAXO.NS', 'SUPREMEIND.NS', 'PAGEIND.NS', 'TIINDIA.NS', 'TITAN.NS', 'TRENT.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'BHARATFORG.NS', 'BOSCHLTD.NS', 'HEROMOTOCO.NS', 'EICHERMOT.NS', 'CROMPTON.NS', 'INDUSTOWER.NS', 'NAUKRI.NS', 'INDIAMART.NS', 'IDEA.NS', 'BHARTIARTL.NS', 'SUNTV.NS', 'TATACOMM.NS', 'ASIANPAINT.NS', 'ULTRACEMCO.NS', 'JSWSTEEL.NS', 'HINDZINC.NS', 'TATASTEEL.NS', 'VEDL.NS', 'SHREECEM.NS', 'PIDILITIND.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BERGEPAINT.NS', 'AMBUJACEM.NS', 'UPL.NS', 'NMDC.NS', 'SAIL.NS', 'JINDALSTEL.NS', 'PIIND.NS', 'SRF.NS', 'ACC.NS', 'DALBHARAT.NS', 'KANSAINER.NS', 'AARTIIND.NS', 'BAYERCROP.NS', 'ATUL.NS', 'DEEPAKNTR.NS', 'COROMANDEL.NS', 'RAMCOCEM.NS', 'JKCEMENT.NS']
    mc = ['BRIGADE.NS',       'PRESTIGE.NS',       'PHOENIXLTD.NS',       'OBEROIRLTY.NS',      'VGUARD.NS',      'SCHAEFFLER.NS',      'SCI.NS',      'CARBORUNIV.NS',      'TEAMLEASE.NS',      'AIAENG.NS',      'THERMAX.NS',      'SUZLON.NS',      'CYIENT.NS',      'DBL.NS',      'TIMKEN.NS',      'SKFINDIA.NS',      'SIS.NS',      'CERA.NS',      'BLUEDART.NS',      'COCHINSHIP.NS',      'BDL.NS',      'BBTC.NS',      'BLUESTARCO.NS',      'CGPOWER.NS',      'PNCINFRA.NS',      'FINCABLES.NS',      'FINPIPE.NS',      'KALPATPOWR.NS',      'GESHIP.NS',      'BEML.NS',      'GMRINFRA.NS',      'MMTC.NS',      'GODREJIND.NS',      'KAJARIACER.NS',      'NBCC.NS',      'GMMPFAUDLR.NS',      'KNRCON.NS',      'ESCORTS.NS',      'LAXMIMACH.NS',      'QUESS.NS',      'HEG.NS',      'RITES.NS',      'KEC.NS',      'ELGIEQUIP.NS',      'GRINDWELL.NS',      'RVNL.NS',      'PRAJIND.NS',      'GRAPHITE.NS',      'FORTIS.NS', 'ORCHPHARMA.NS', 'ERIS.NS', 'APLLTD.NS', 'SOLARA.NS', 'AJANTPHARM.NS', 'JBCHEPHARM.NS', 'SPARC.NS', 'STAR.NS', 'SANOFI.NS', 'SEQUENT.NS', 'PGHL.NS', 'FDC.NS', 'POLYMED.NS', 'GLENMARK.NS', 'GRANULES.NS', 'AARTIDRUGS.NS', 'NATCOPHARM.NS', 'THYROCARE.NS', 'ASTERDM.NS', 'ASTRAZEN.NS', 'METROPOLIS.NS', 'JUBLPHARMA.NS', 'JUBLINGREA.NS', 'WOCKPHARMA.NS', 'NH.NS', 'SUVENPHAR.NS', 'CHOLAHLDNG.NS', 'CREDITACC.NS', 'PNBHOUSING.NS', 'MOTILALOFS.NS', 'CRISIL.NS', 'MCX.NS', 'CUB.NS', 'IDFC.NS', 'UJJIVANSFB.NS', 'UCOBANK.NS', 'IEX.NS', 'INDIANB.NS', 'TATAINVEST.NS', 'JMFINANCIL.NS', 'IIFLWAM.NS', 'IIFL.NS', 'FEDERALBNK.NS', 'M&MFIN.NS', 'HUDCO.NS', 'CDSL.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'ISEC.NS', 'CAMS.NS', 'AAVAS.NS', 'CENTRALBK.NS', 'SHRIRAMCIT.NS', 'DHANI.NS', 'UTIAMC.NS', 'PSB.NS', 'EDELWEISS.NS', 'ANGELBRKG.NS', 'IBULHSGFIN.NS', 'CANFINHOME.NS', 'EQUITASBNK.NS', 'MANAPPURAM.NS', 'MRPL.NS',  'OIL.NS',  'AEGISCHEM.NS', 'AVANTIFEED.NS', 'KRBL.NS', 'GILLETTE.NS', 'GODREJAGRO.NS', 'RADICO.NS', 'EIDPARRY.NS', 'ZYDUSWELL.NS', 'JYOTHYLAB.NS', 'HATSUN.NS', 'BALRAMCHIN.NS', 'LUXIND.NS', 'VARROC.NS', 'MAHINDCIE.NS', 'MINDAIND.NS', 'ABFRL.NS', 'WELSPUNIND.NS', 'WESTLIFE.NS', 'INDHOTEL.NS', 'BATAINDIA.NS', 'KALYANKJIL.NS', 'VMART.NS', 'VTL.NS', 'WABCOINDIA.NS', 'KPRMILL.NS', 'TRIDENT.NS', 'SUNDRMFAST.NS', 'ALOKINDS.NS', 'AMARAJABAT.NS', 'SFL.NS', 'SUNCLAYLTD.NS', 'ORIENTELEC.NS', 'TTKPRESTIG.NS', 'ASAHIINDIA.NS', 'RAJESHEXPO.NS', 'SYMPHONY.NS', 'APOLLOTYRE.NS', 'GARFIBRES.NS', 'EXIDEIND.NS', 'EPL.NS', 'ENDURANCE.NS', 'EIHOTEL.NS', 'CENTURYPLY.NS', 'CEATLTD.NS', 'JAINSTUDIO.NS', 'JAGRAN.NS', 'RCOM.NS', 'INOXLEISUR.NS', 'ROUTE.NS', 'SABEVENTS.NS', 'SABTN.NS', 'INDUSTOWER.NS', 'SAMBHAAV.NS', 'SANDESH.NS', 'SAREGAMA.NS', 'NAUKRI.NS', 'INDIAMART.NS', 'MATRIMONY.NS', 'DNAMEDIA.NS', 'SHEMAROO.NS', 'DISHTV.NS', 'IMAGICAA.NS', 'IDEA.NS', 'HTMEDIA.NS', 'SILLYMONKS.NS', 'DGCONTENT.NS', 'SITINET.NS', 'ENIL.NS', 'SCHAND.NS', 'RAJTV.NS', 'EROSMEDIA.NS', 'NAVNETEDUL.NS', 'NAZARA.NS', 'NDTV.NS', 'NETWORK18.NS', 'NEXTMEDIA.NS', 'DEN.NS', 'BHARTIARTL.NS', 'NXTDIGITAL.NS', 'ONMOBILE.NS', 'GFLLIMITED.NS', 'GTL.NS', 'ORTEL.NS', 'GTPL.NS', 'PFOCUS.NS', 'PNC.NS', 'MUKTAARTS.NS', 'JUSTDIAL.NS', 'PRESSMN.NS', 'MTNL.NS', 'BALAJITELE.NS', 'HATHWAY.NS', 'MPSLTD.NS', 'BCG.NS', 'RADAAN.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'BAGFILMS.NS', 'PVR.NS', 'HMVL.NS', 'TV18BRDCST.NS', 'DALALSTCOM.NS', 'UFO.NS', 'CYBERMEDIA.NS', 'TIPSINDLTD.NS', 'DBCORP.NS', 'SUNTV.NS', 'TATACOMM.NS', 'TVVISION.NS', 'ZEEL.NS', 'TOUCHWOOD.NS', 'AFFLE.NS', 'TVTODAY.NS', 'ZEEMEDIA.NS', 'CINEVISTA.NS', 'VERTOZ.NS', 'CREATIVEYE.NS', 'TTML.NS', 'ASIANPAINT.NS', 'ULTRACEMCO.NS', 'JSWSTEEL.NS', 'HINDZINC.NS', 'TATASTEEL.NS', 'VEDL.NS', 'SHREECEM.NS', 'PIDILITIND.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BERGEPAINT.NS', 'AMBUJACEM.NS', 'UPL.NS', 'NMDC.NS', 'SAIL.NS', 'JINDALSTEL.NS', 'PIIND.NS', 'SRF.NS', 'ACC.NS', 'DALBHARAT.NS', 'KANSAINER.NS', 'AARTIIND.NS', 'BAYERCROP.NS', 'ATUL.NS', 'DEEPAKNTR.NS', 'COROMANDEL.NS', 'RAMCOCEM.NS', 'JKCEMENT.NS', 'TATACHEM.NS', 'VINATIORGA.NS', 'HINDCOPPER.NS', 'NAVINFLUOR.NS', 'SUMICHEM.NS', 'APLAPOLLO.NS', 'LINDEINDIA.NS', 'NATIONALUM.NS', 'CASTROLIND.NS', 'KIOCL.NS', 'INDIGOPNTS.NS', 'CHAMBLFERT.NS', 'SOLARINDS.NS', 'BASF.NS', 'TATASTLBSL.NS', 'DCMSHRIRAM.NS', 'GALAXYSURF.NS', 'AKZOINDIA.NS', 'FINEORG.NS', 'FLUOROCHEM.NS', 'RATNAMANI.NS', 'FACT.NS', 'BIRLACORPN.NS', 'BALAMINES.NS', 'ALKYLAMINE.NS', 'ANURAS.NS', 'ROSSARI.NS', 'PRSMJOHNSN.NS', 'PRINCEPIPE.NS', 'SUPPETRO.NS', 'GNFC.NS', 'RALLIS.NS', 'LXCHEM.NS', 'RAIN.NS', 'BHARATRAS.NS', 'CENTURYTEX.NS', 'INDIACEM.NS', 'HEIDELBERG.NS', 'ADVENZYMES.NS', 'VALIANTORG.NS', 'JKLAKSHMI.NS', 'GSFC.NS', 'SUDARSCHEM.NS', 'RCF.NS', 'JSL.NS', 'TATASTLLP.NS', 'RESPONIND.NS', 'MOIL.NS', 'DHANUKA.NS', 'STARCEMENT.NS', 'PRIVISCL.NS', 'JSLHISAR.NS', 'MIDHANI.NS', 'WELCORP.NS', 'GULFOILLUB.NS', 'PHILIPCARB.NS', 'MEGH.NS', 'JINDALPOLY.NS', 'POLYPLEX.NS', 'NFL.NS', 'GPIL.NS', 'NOCIL.NS', 'TATAMETALI.NS', 'GUJALKALI.NS', 'SHARDACROP.NS', 'HERANBA.NS', 'JSWISPL.NS', 'DEEPAKFERT.NS', 'JINDALSAW.NS', 'OAL.NS', 'BEPL.NS', 'ASTEC.NS', 'JKPAPER.NS', 'GREENPLY.NS', 'ORIENTCEM.NS', 'GHCL.NS', 'SURYAROSNI.NS', 'MAITHANALL.NS', 'INEOSSTYRO.NS', 'CAMLINFINE.NS', 'TINPLATE.NS', 'HSCL.NS', 'NEOGEN.NS', 'MAHSEAMLES.NS', 'SARDAEN.NS', 'SAGCEM.NS', 'TIDEWATER.NS', 'JAICORPLTD.NS', 'MUKANDLTD.NS', 'CHEMCON.NS', 'APCOTEXIND.NS', 'PRAKASH.NS', 'KIRIINDUS.NS', 'USHAMART.NS', 'KSL.NS', 'ORISSAMINE.NS', 'INDIAGLYCO.NS', 'GALLISPAT.NS', 'SOTL.NS', 'SUNFLAG.NS', 'IGPL.NS', 'PUNJABCHEM.NS', 'KCP.NS', 'MANALIPETC.NS', 'ELECTCAST.NS', 'EXCELINDUS.NS', 'ASHAPURMIN.NS', 'WSTCSTPAPR.NS', 'IFGLEXPOR.NS', 'KESORAMIND.NS', 'ESTER.NS', 'JAYNECOIND.NS', 'BODALCHEM.NS', 'SANGHIIND.NS', 'IMFA.NS', 'MANGCHEFER.NS', 'ANDHRSUGAR.NS', 'AARTISURF.NS', 'INSECTICID.NS', 'CLNINDIA.NS', 'FAIRCHEMOR.NS', 'KINGFA.NS', 'TIRUMALCHM.NS', 'SHREDIGCEM.NS', 'RAJRATAN.NS', 'NACLIND.NS', 'VIDHIING.NS', 'GOCLCORP.NS', 'SESHAPAPER.NS', 'TNPL.NS', 'OCCL.NS', 'SIRCA.NS', 'ANDHRAPAP.NS', 'FCL.NS', 'BHAGERIA.NS', 'FOSECOIND.NS', 'DCW.NS', 'NCLIND.NS', 'SPIC.NS', 'SATIA.NS', 'NATHBIOGEN.NS', 'AVTNPL.NS', 'TNPETRO.NS', 'VSSL.NS', 'MANGLMCEM.NS', 'SALASAR.NS', 'GULPOLY.NS', 'UNIENTER.NS', 'PLASTIBLEN.NS', 'DECCANCE.NS', 'BESTAGRO.NS', 'KUANTUM.NS', 'APCL.NS', 'DYNPRO.NS', 'KANORICHEM.NS', 'MANINDS.NS', 'JAIBALAJI.NS', 'ORIENTPPR.NS', 'JAYAGROGN.NS', 'SHREEPUSHK.NS', 'GALLANTT.NS', 'STEELXIND.NS', 'SHALPAINTS.NS', 'NAGAFERT.NS', 'SRHHYPOLTD.NS', 'JUBLINDS.NS', 'MADRASFERT.NS', 'ASAHISONG.NS', 'MSPL.NS', 'ZUARI.NS', 'KAMDHENU.NS', 'NRAIL.NS', 'HITECH.NS', 'VISHNU.NS', 'BHARATWIRE.NS', 'DICIND.NS', 'GSCLCEMENT.NS', 'CHEMBOND.NS', 'ORIENTABRA.NS', 'GOACARBON.NS', 'VINYLINDIA.NS', 'ISMTLTD.NS', 'MCL.NS', 'PODDARMENT.NS', 'RAMANEWS.NS', 'AKSHARCHEM.NS', 'MMP.NS', 'KOTHARIPET.NS', 'AGARIND.NS', 'PDMJEPAPER.NS', 'ARVEE.NS', 'KRISHANA.NS', 'CHEMFAB.NS', 'GENUSPAPER.NS', 'STARPAPER.NS', 'SHYAMCENT.NS', 'ASTRON.NS', 'KAKATCEM.NS', 'MBAPL.NS', 'ANDHRACEMT.NS', 'MANAKSTEEL.NS', 'BALLARPUR.NS', 'BHAGYANGR.NS', '20MICRONS.NS', 'PREMEXPLN.NS', 'BSHSL.NS', 'RUCHIRA.NS', 'JOCIL.NS', 'ARIES.NS', 'SEYAIND.NS', 'ADHUNIKIND.NS', 'MAHASTEEL.NS', 'MAANALU.NS', 'XPROINDIA.NS', 'RAMASTEEL.NS', 'SHREYANIND.NS', 'VISASTEEL.NS', 'UTTAMSTL.NS', 'IVP.NS', 'SHRENIK.NS', 'VIKASWSP.NS', 'RAJMET.NS', 'VIKASPROP.NS', 'SIGIND.NS', 'MANAKALUCO.NS', 'PREMIERPOL.NS', 'SICAGEN.NS', 'BEDMUTHA.NS', 'ABMINTLTD.NS', 'SAGARDEEP.NS', 'VIKASECO.NS', 'ARCHIDPLY.NS', 'SUPREMEENG.NS', 'TAINWALCHM.NS', 'HISARMETAL.NS', 'ALKALI.NS', 'SUNDARAM.NS', 'CENTEXT.NS', 'WIPL.NS', 'GAL.NS', 'MALUPAPER.NS', 'CUBEXTUB.NS', 'BVCL.NS', 'VASWANI.NS', 'SALSTEEL.NS', 'SANGINITA.NS', 'KRIDHANINF.NS', 'ROHITFERRO.NS', 'AGROPHOS.NS', 'NATNLSTEEL.NS', 'BURNPUR.NS', 'PRAKASHSTL.NS', 'SEPOWER.NS', 'MANGTIMBER.NS', 'ANKITMETAL.NS', 'MAGNUM.NS', 'ZENITHSTL.NS', 'JIYAECO.NS', 'IMPEXFERRO.NS', 'SMPL.NS', 'GFSTEELS.NS', 'NTL.NS', 'ARENTERP.NS'] 
    sc = ['RTNINDIA.NS', 'RPOWER.NS', 'RTNPOWER.NS', 'DPSCLTD.NS', 'RELINFRA.NS', 'GIPCL.NS', 'INDOWIND.NS', 'KARMAENG.NS', 'PTC.NS', 'GREENPOWER.NS', 'NBVENTURES.NS', 'ENERGYDEV.NS', 'JPPOWER.NS', 'SURANAT&P.NS', 'MIC.NS', 'UJAAS.NS', 'CENTUM.NS', 'MINDTECK.NS', 'XCHANGING.NS', 'KELLTONTEC.NS', '3IINFOTECH.NS', 'MASTEK.NS', 'XELPMOC.NS', 'AURIONPRO.NS', 'GTLINFRA.NS', 'ACCELYA.NS', 'MAJESCO.NS', 'GSS.NS', 'WEBELSOLAR.NS', 'ASTRAMICRO.NS', 'CEREBRAINT.NS', 'JUMPNET.NS', 'GOLDTECH.NS', 'MEGASOFT.NS', 'MELSTAR.NS', 'URJA.NS', 'CALSOFT.NS', 'HOVS.NS', 'IFBIND.NS', 'EXPLEOSOL.NS', 'BIRLACABLE.NS', 'FCSSOFT.NS', 'AIRAN.NS', 'PGEL.NS', 'SMARTLINK.NS', 'PARACABLES.NS', 'PALREDTEC.NS', 'HCL-INSYS.NS', 'SUBEXLTD.NS', 'DATAMATICS.NS', 'AGCNET.NS', 'BARTRONICS.NS', 'CYBERTECH.NS', 'PANACHE.NS', 'QUICKHEAL.NS', 'INFOBEAN.NS', 'ECLERX.NS', 'INTENTECH.NS', 'DSSL.NS', 'RSYSTEMS.NS', 'RSSOFTWARE.NS', 'SASKEN.NS', 'ROLTA.NS', 'DRCSYSTEMS.NS', 'INSPIRISYS.NS', 'SECURKLOUD.NS', 'HFCL.NS', 'IZMO.NS', 'DLINKINDIA.NS', 'DIGISPICE.NS', 'RAMCOSYS.NS', 'ALANKIT.NS', 'AKSHOPTFBR.NS', 'SHYAMTEL.NS', 'OPTIEMUS.NS', 'ONWARDTEC.NS', 'INDOSOLAR.NS', 'TEJASNET.NS', 'BPL.NS', 'NEWGEN.NS', 'SURANASOL.NS', 'NELCO.NS', 'TERASOFT.NS', 'COMPINFO.NS', 'GENESYS.NS', 'TNTELE.NS', 'MRO-TEK.NS', 'TREJHARA.NS', 'TRIGYN.NS', 'CIGNITITEC.NS', 'TVSELECT.NS', 'SAKSOFT.NS', 'KERNEX.NS', 'SWELECTES.NS', 'SWSOLAR.NS', 'NUCLEUS.NS', 'CREATIVE.NS', 'SUVIDHAA.NS', 'ADSL.NS', 'ADROITINFO.NS', 'CTE.NS', 'KOLTEPATIL.NS', 'TECHIN.NS', 'EMAMIREAL.NS', 'TCIDEVELOP.NS', 'CINELINE.NS', 'MODIRUBBER.NS', 'TEXINFRA.NS', 'RVHL.NS', 'MOTOGENFIN.NS', 'ARVSMART.NS', 'GEECEE.NS', 'BHAGYAPROP.NS', 'UNITECH.NS', 'ASHIANA.NS', 'AMJLAND.NS', 'ANANTRAJ.NS', 'COUNCODOS.NS', 'DBREALTY.NS', 'NILASPACES.NS', 'ARIHANTSUP.NS', 'SUNTECK.NS', 'PTL.NS', 'ARIHANT.NS', 'NILAINFRA.NS', 'FMNL.NS', 'SUMIT.NS', 'OSWALAGRO.NS', 'VIPULLTD.NS', 'HUBTOWN.NS', 'KARDA.NS', 'HDIL.NS', 'PARSVNATH.NS', 'PENINLAND.NS', 'SOBHA.NS', 'AJMERA.NS', 'PRAENG.NS', 'LPDC.NS', 'BOMDYEING.NS', 'PODDARHOUS.NS', 'MAHLIFE.NS', 'OMAXE.NS', 'PROZONINTU.NS', 'IBREALEST.NS', 'TARC.NS', 'BSELINFRA.NS', 'SHRADHA.NS', 'ANSALAPI.NS', 'ANSALHSG.NS', 'HEMIPROP.NS', 'MARATHON.NS', 'GANESHHOUC.NS', 'INGERRAND.NS', 'VINDHYATEL.NS', 'VISAKAIND.NS', 'AARVI.NS', 'CEBBCO.NS', 'SALZERELEC.NS', 'ZENTEC.NS', 'SHANTIGEAR.NS', 'BLS.NS', 'ALICON.NS', 'VETO.NS', 'VESUVIUS.NS', 'BLKASHYAP.NS', 'ICEMAKE.NS', 'SHREYAS.NS', 'VASCONEQ.NS', 'SANCO.NS', 'CAPACITE.NS', 'WALCHANNAG.NS', 'AARON.NS', 'WELENT.NS', 'WABAG.NS', 'SCHNEIDER.NS', 'VSTTILLERS.NS', 'SEAMECLTD.NS', 'DREDGECORP.NS', 'HONDAPOWER.NS', 'ALLSEC.NS', 'WENDT.NS', 'ALLCARGO.NS', 'DPWIRES.NS', 'SETUINFRA.NS', 'VRLLOG.NS', 'CANDC.NS', 'INOXWIND.NS', 'SHAKTIPUMP.NS', 'VOLTAMP.NS', 'WINDMACHIN.NS', 'HPL.NS', 'WSI.NS', 'SANGHVIMOV.NS', 'HLEGLAS.NS', 'DUCON.NS', 'CCCL.NS', 'A2ZINFRA.NS', 'ACCURACY.NS', 'SICAL.NS', 'TCI.NS', 'TCIEXP.NS', 'TDPOWERSYS.NS', 'INDOTECH.NS', 'SRIPIPES.NS', 'TECHNOE.NS', 'AHLUCONT.NS', 'TEXMOPIPES.NS', 'TEXRAIL.NS', 'DCM.NS', 'TIIL.NS', 'TIJARIA.NS', 'TEMBO.NS', 'CONTROLPR.NS', 'STCINDIA.NS', 'IL&FSTRANS.NS', 'INDIANHUME.NS', 'INDLMETER.NS', 'SUNDARMHLD.NS', 'HILTON.NS', 'BEARDSELL.NS', 'TANTIACONS.NS', 'HIL.NS', 'STERTOOLS.NS', 'TARAPUR.NS', 'TARMAT.NS', 'AHLADA.NS', 'ADORWELD.NS', 'CORDSCABLE.NS', 'TIL.NS', 'BBL.NS', 'SPMLINFRA.NS', 'UNIVASTU.NS', 'UNIVCABLES.NS', 'SKIPPER.NS', 'SKIL.NS', 'DELTAMAGNT.NS', 'DENORA.NS', 'AKASH.NS', 'HGS.NS', 'SIMPLEXINF.NS', 'HGINFRA.NS', 'BCP.NS', 'ACE.NS', 'SHRIRAMEPC.NS', 'HIRECT.NS', 'TWL.NS', 'SPICEJET.NS', 'TIRUPATIFL.NS', 'CMICABLES.NS', 'TOTAL.NS', 'TRF.NS', 'TRIL.NS', 'TRITURBINE.NS', 'SORILINFRA.NS', 'SOMICONVEY.NS', 'BRNL.NS', 'SOMANYCERA.NS', 'SNOWMAN.NS', 'IL&FSENGG.NS', 'EKC.NS', 'NIRAJ.NS', 'MAHEPC.NS', 'BALMLAWRIE.NS', 'ONEPOINT.NS', 'MAHESHWARI.NS', 'MAHLOG.NS', 'OMINFRAL.NS', 'GUJAPOLLO.NS', 'JKIL.NS', 'AROGRANITE.NS', 'BIGBLOC.NS', 'ATLANTA.NS', 'MANAKCOAT.NS', 'MANAKSIA.NS', 'MANINFRA.NS', 'GAMMNINFRA.NS', 'ARSHIYA.NS', 'NOIDATOLL.NS', 'MANUGRAPH.NS', 'ARSSINFRA.NS', 'GANDHITUBE.NS', 'HCC.NS', 'MADHUCON.NS', 'ORIENTALTL.NS', 'ORIENTBELL.NS', 'MADHAV.NS', 'APOLLOPIPE.NS', 'LOKESHMACH.NS', 'PITTIENG.NS', 'LSIL.NS', 'JETAIRWAYS.NS', 'PENIND.NS', 'PDSMFL.NS', 'NITINFIRE.NS', 'PATINTLOG.NS', 'GPTINFRA.NS', 'GPPL.NS', 'GOODLUCK.NS', 'JISLDVREQS.NS', 'PAEL.NS', 'KAPSTON.NS', 'MACPOWER.NS', 'JISLJALEQS.NS', 'ORIENTREF.NS', 'JITFINFRA.NS', 'FSC.NS', 'PATELENG.NS', 'POKARNA.NS', 'MARINE.NS', 'JPINFRATEC.NS', 'GEPIL.NS', 'GET&D.NS', 'MURUDCERA.NS', 'GILLANDERS.NS', 'ASIANTILES.NS', 'MTARTECH.NS', 'MEP.NS', 'MSTCLTD.NS', 'ASHOKA.NS', 'METALFORGE.NS', 'GISOLUTION.NS', 'GKWLIMITED.NS', 'MOLDTECH.NS', 'JSWHL.NS', 'GLOBALVECT.NS', 'MODISNME.NS', 'MMFL.NS', 'GENUSPOWER.NS', 'MBLINFRA.NS', 'MBECL.NS', 'JYOTISTRUC.NS', 'NIPPOBATRY.NS', 'HBLPOWER.NS', 'NIBL.NS', 'JMCPROJECT.NS', 'GATI.NS', 'NESCO.NS', 'KABRAEXTRU.NS', 'GAYAHWS.NS', 'NITCO.NS', 'GODHA.NS', 'MAZDOCK.NS', 'NELCAST.NS', 'NECCLTD.NS', 'GAYAPROJ.NS', 'JPASSOCIAT.NS', 'GDL.NS', 'NCC.NS', 'GEEKAYWIRE.NS', 'NAVKARCORP.NS', 'GENCON.NS', 'MAZDA.NS', 'RNAVAL.NS', 'KSB.NS', 'RKEC.NS', 'LAKPRE.NS', 'KEI.NS', 'BGRENERGY.NS', 'ESABINDIA.NS', 'RKFORGE.NS', 'ELECON.NS', 'GRSE.NS', 'PURVA.NS', 'AWHCL.NS', 'KENNAMET.NS', 'ESSARSHPNG.NS', 'PUNJLLOYD.NS', 'ANUP.NS', 'EMCO.NS', 'KECL.NS', 'KOKUYOCMLN.NS', 'HERCULES.NS', 'HMT.NS', 'REPL.NS', 'REPRO.NS', 'ITDCEM.NS', 'REVATHI.NS', 'ZUARIGLOB.NS', 'RAMCOIND.NS', 'ENGINERSIN.NS', 'BANKA.NS', 'ELECTHERM.NS', 'RIIL.NS', 'RAMKY.NS', 'JASH.NS', 'KOTHARIPRO.NS', 'KIRLOSIND.NS', 'EASUNREYRL.NS', 'IRCON.NS', 'PREMIER.NS', 'PRECWIRE.NS', 'ROLLT.NS', 'GREAVESCOT.NS', 'GRAVITA.NS', 'APOLLO.NS', 'S&SPOWER.NS', 'SADBHAV.NS', 'LINCPEN.NS', 'PPL.NS', 'BFUTILITIE.NS', 'LGBFORGE.NS', 'AXISCADES.NS', 'PSPPROJECT.NS', 'APARINDS.NS', 'EIMCOELECO.NS', 'KIRLOSENG.NS', 'RPPINFRA.NS', 'IRB.NS', 'KAUSHALYA.NS', 'EVEREADY.NS', 'EVERESTIND.NS', 'KIRLFER.NS', 'POWERMECH.NS', 'EXCEL.NS', 'KIRLOSBROS.NS', 'SADBHIN.NS', 'PANACEABIO.NS', 'ALPA.NS', 'ORTINLAB.NS', 'IOLCP.NS', 'HESTERBIO.NS', 'BALPHARMA.NS', 'INDOCO.NS', 'OPTOCIRCUI.NS', 'HIKAL.NS', 'INDSWFTLTD.NS', 'INDSWFTLAB.NS', 'SMSLIFE.NS', 'SMSPHARMA.NS', 'JAGSNPHARM.NS', 'ALBERTDAVD.NS', 'ALEMBICLTD.NS', 'INDRAMEDCO.NS', 'SHILPAMED.NS', 'SASTASUNDR.NS', 'DCAL.NS', 'RPGLIFE.NS', 'BIOFILCHEM.NS', 'BLISSGVS.NS', 'SHALBY.NS', 'AMRUTANJAN.NS', 'SUVEN.NS', 'MOREPENLAB.NS', 'VIVIMEDLAB.NS', 'MARKSANS.NS', 'THEMISMED.NS', 'LINCOLN.NS', 'NECLIFE.NS', 'CAPLIPOINT.NS', 'TTKHLTCARE.NS', 'BROOKS.NS', 'MAXIND.NS', 'VENUSREM.NS', 'MANGALAM.NS', 'GUFICBIO.NS', 'UNIVPHOTO.NS', 'VIMTALABS.NS', 'UNICHEMLAB.NS', 'LYKALABS.NS', 'WANBURY.NS', 'LOTUSEYE.NS', 'VAISHALI.NS', 'KREBSBIO.NS', 'KILITCH.NS', 'TAKE.NS', 'SAKAR.NS', 'NOVARTIND.NS', 'KOPRAN.NS', 'SYNCOM.NS', 'ZOTA.NS', 'HCG.NS', 'BAFNAPH.NS', 'NEULANDLAB.NS', 'LASA.NS', 'NURECA.NS', 'IFCI.NS', 'ARMANFIN.NS', 'GLFL.NS', 'SOUTHBANK.NS', 'TCIFINANCE.NS', 'SPANDANA.NS', 'PNBGILTS.NS', 'NSIL.NS', 'BINDALAGRO.NS', 'CREST.NS', 'ONELIFECAP.NS', 'UJJIVAN.NS', 'CSBBANK.NS', 'SURYODAY.NS', 'BIRLAMONEY.NS', 'SUMMITSEC.NS', 'INDOSTAR.NS', 'NBIFIN.NS', 'SREINFRA.NS', 'THEINVEST.NS', 'IITL.NS', 'STEELCITY.NS', 'NDGL.NS', 'PFS.NS', 'TFL.NS', 'TFCILTD.NS', 'DCBBANK.NS', 'DBSTOCKBRO.NS', 'CONSOFINVT.NS', 'IIFLSEC.NS', 'JINDALPHOT.NS', 'MUTHOOTCAP.NS', 'GICHSGFIN.NS', 'INDBANK.NS', 'NAGREEKCAP.NS', 'PAISALO.NS', 'INDOTHAI.NS', 'PILANIINVS.NS', 'TIMESGTY.NS', 'HBSL.NS', 'GEOJITFSL.NS', 'NAHARCAP.NS', 'DCMFINSERV.NS', 'VLSFINANCE.NS', 'REPCOHOME.NS', 'IVC.NS', 'MCDHOLDING.NS', '5PAISA.NS', 'RELIGARE.NS', 'RELCAPITAL.NS', 'CARERATING.NS', 'HEXATRADEX.NS', 'BLBLIMITED.NS', 'DOLAT.NS', 'MAGMA.NS', 'MAHAPEXLTD.NS', 'AUSOMENT.NS', 'RHFL.NS', 'CAPTRUST.NS', 'KTKBANK.NS', 'WILLAMAGOR.NS', 'WELINV.NS', 'RPSGVENT.NS', 'ALMONDZ.NS', 'SATIN.NS', 'WEALTH.NS', 'KARURVYSYA.NS', 'LFIC.NS', 'HOTELRUGBY.NS', 'SCAPDVR.NS', 'SHAREINDIA.NS', 'EMKAY.NS', 'VIJIFIN.NS', 'J&KBANK.NS', 'DHFL.NS', 'CENTRUM.NS', 'KICL.NS', 'KHANDSE.NS', 'MASFIN.NS', 'MASKINVEST.NS', 'EBIXFOREX.NS', 'BFINVEST.NS', 'KEYFINSERV.NS', 'SILINV.NS', 'DHANBANK.NS', 'BSE.NS', 'ICRA.NS', 'PRIMESECU.NS', 'YAARII.NS', 'DVL.NS', 'HOMEFIRST.NS', 'VHL.NS', 'INVENTURE.NS', 'INFOMEDIA.NS', 'EQUITAS.NS', 'DHUNINV.NS', 'CONFIPET.NS', 'UNIDT.NS', 'MERCATOR.NS', 'LIKHITHA.NS', 'SELAN.NS', 'GMDCLTD.NS', 'REFEX.NS', 'CHENNPETRO.NS', 'DEEPINDS.NS', 'GULFPETRO.NS', 'SOUTHWEST.NS', 'DEEPENR.NS', 'ABAN.NS', 'ALPHAGEO.NS', 'AAKASH.NS', 'JINDRILL.NS', 'PANAMAPET.NS', 'HINDOILEXP.NS', 'LIBERTSHOE.NS', 'V2RETAIL.NS', 'MARALOVER.NS', 'LAOPALA.NS', 'LEMONTREE.NS', 'VAIBHAVGBL.NS', 'VARDHACRLC.NS', 'ATULAUTO.NS', 'MAHSCOOTER.NS', 'LYPSAGEMS.NS', 'LIBAS.NS', 'AUTOAXLES.NS', 'VARDMNPOLY.NS', 'LGBBROSLTD.NS', 'LUMAXIND.NS', 'LOVABLE.NS', 'AUTOIND.NS', 'LUMAXTECH.NS', 'MHRIL.NS', 'MAYURUNIQ.NS', 'NAHARSPING.NS', 'NAHARPOLY.NS', 'NAHARINDUS.NS', 'TVSSRICHAK.NS', 'NAGREEKEXP.NS', 'MUNJALSHOW.NS', 'MUNJALAU.NS', 'ASHIMASYN.NS', 'UCALFUEL.NS', 'UFLEX.NS', 'MAXVIL.NS', 'MORARJEE.NS', 'MOLDTKPAC.NS', 'MOHOTAIND.NS', 'MOHITIND.NS', 'ASIANHOTNR.NS', 'BURGERKING.NS', 'MIRZAINT.NS', 'MIRCELECTR.NS', 'MINDACORP.NS', 'LAMBODHARA.NS', 'MENONBE.NS', 'ACRYSIL.NS', 'MONTECARLO.NS', 'SPENTEX.NS', 'KKCL.NS', 'JAMNAAUTO.NS', 'WEIZMANIND.NS', 'BANG.NS', 'ITDC.NS', 'ISFT.NS', 'IRISDOREME.NS', 'BANSWRAS.NS', 'WHEELS.NS', 'BARBEQUE.NS', 'WONDERLA.NS', 'INDTERRAIN.NS', 'JAYBARMARU.NS', 'INDORAMA.NS', 'INDIANCARD.NS', 'WORTH.NS', 'BASML.NS', 'IMPAL.NS', 'ZENITHEXPO.NS', 'IGARASHI.NS', 'ZODIACLOTH.NS', 'ICIL.NS', 'HUHTAMAKI.NS', 'ZODJRDMKJ.NS', 'HSIL.NS', 'INDNIPPON.NS', 'BANCOINDIA.NS', 'JBFIND.NS', 'JBMA.NS', 'KITEX.NS', 'AYMSYNTEX.NS', 'KDDL.NS', 'VICEROY.NS', 'KANPRPLA.NS', 'VIDEOIND.NS', 'KANANIIND.NS', 'AARVEEDEN.NS', 'KAMATHOTEL.NS', 'VIPCLOTHNG.NS', 'VIPIND.NS', 'KALYANIFRG.NS', 'VISHAL.NS', 'JTEKTINDIA.NS', 'VIVIDHA.NS', 'BALKRISHNA.NS', 'JMTAUTOLTD.NS', 'JMA.NS', 'JKTYRE.NS', 'JINDWORLD.NS', 'BANARBEADS.NS', 'JIKIND.NS', 'KHADIM.NS', 'TTL.NS', 'SETCO.NS', 'SARLAPOLY.NS', 'SANGAMIND.NS', 'SANDHAR.NS', 'ALPSINDUS.NS', 'SALONA.NS', 'AMBIKCO.NS', 'SUPERHOUSE.NS', 'SAFARI.NS', 'SUPERSPIN.NS', 'SUNDRMBRAK.NS', 'RUSHIL.NS', 'AMDIND.NS', 'RUBYMILLS.NS', 'RSWM.NS', 'SUPRAJIT.NS', 'ROHLTD.NS', 'RML.NS', 'RMCL.NS', 'RICOAUTO.NS', 'RGL.NS', 'REMSONSIND.NS', 'SURYALAXMI.NS', 'RUPA.NS', 'RBL.NS', 'SHANKARA.NS', 'SPENCERS.NS', 'SPTL.NS', 'SPECIALITY.NS', 'SPAL.NS', 'SOMATEX.NS', 'SMLISUZU.NS', 'SIYSIL.NS', 'SPYL.NS', 'SREEL.NS', 'SINTEX.NS', 'AHLWEST.NS', 'SINTERCOM.NS', 'SSWL.NS', 'SGL.NS', 'SILGO.NS', 'AHLEAST.NS', 'SHRIPISTON.NS', 'STOVEKRAFT.NS', 'SHREERAMA.NS', 'SHOPERSTOP.NS', 'SHIVATEX.NS', 'SHIVAMILLS.NS', 'SHIVAMAUTO.NS', 'SHIL.NS', 'SUBROS.NS', 'SHARDAMOTR.NS', 'SUMEETINDS.NS', 'SIL.NS', 'ASAL.NS', 'RAYMOND.NS', 'RANEHOLDIN.NS', 'PCJEWELLER.NS', 'PATSPINLTD.NS', 'THOMASCOTT.NS', 'TIMETECHNO.NS', 'ORIENTLTD.NS', 'ORIENTHOT.NS', 'ORICONENT.NS', 'ORBTEXP.NS', 'OMAXAUTO.NS', 'OLECTRA.NS', 'ARCHIES.NS', 'TMRVL.NS', 'NRBBEARING.NS', 'TOKYOPLAST.NS', 'NITINSPIN.NS', 'NILKAMAL.NS', 'ARVIND.NS', 'ARVINDFASN.NS', 'NDRAUTO.NS', 'NDL.NS', 'SPLIL.NS', 'ARROWGREEN.NS', 'ADVANIHOTR.NS', 'PEARLPOLY.NS', 'PGIL.NS', 'RANEENGINE.NS', 'SUTLEJTEX.NS', 'SUULD.NS', 'SWANENERGY.NS', 'SWARAJENG.NS', 'RAJRAYON.NS', 'TAJGVK.NS', 'TALBROAUTO.NS', 'ADL.NS', 'THOMASCOOK.NS', 'PRICOLLTD.NS', 'TCNSBRANDS.NS', 'PRECOT.NS', 'PRECAM.NS', 'TCPLPACK.NS', 'PRAXIS.NS', 'PRADIP.NS', 'PPAP.NS', 'TGBHOTELS.NS', 'PIONEEREMB.NS', 'PILITA.NS', 'APOLSINHOT.NS', 'THANGAMAYL.NS', 'TBZ.NS', 'BUTTERFLY.NS', 'MITTAL.NS', 'HLVLTD.NS', 'GANECOS.NS', 'DPABHUSHAN.NS', 'DONEAR.NS', 'DOLLAR.NS', 'HAVISHA.NS', 'GBGLOBAL.NS', 'BHARATGEAR.NS', 'GINNIFILA.NS', 'DYNAMATECH.NS', 'DELTACORP.NS', 'BOROLTD.NS', 'BORORENEW.NS', 'DCMNVL.NS', 'GNA.NS', 'FELDVR.NS', 'DAMODARIND.NS', 'BHANDARI.NS', 'GLOBE.NS', 'EASEMYTRIP.NS', 'EASTSILK.NS', 'BIL.NS', 'FIEMIND.NS', 'FILATEX.NS', 'BIRLATYRE.NS', 'EUROTEXIND.NS', 'BKMINDST.NS', 'FLEXITUFF.NS', 'FLFL.NS', 'EMMBI.NS', 'ELGIRUBCO.NS', 'FMGOETZE.NS', 'FORCEMOT.NS', 'FRETAIL.NS', 'EIHAHOTELS.NS', 'GRPLTD.NS', 'GABRIEL.NS', 'HIMATSEIDE.NS', 'DANGEE.NS', 'HINDCOMPOS.NS', 'GOKEX.NS', 'CHALET.NS', 'CRAFTSMAN.NS', 'GOLDIAM.NS', 'GOODYEAR.NS', 'GREENLAM.NS', 'GREENPANEL.NS', 'BRFL.NS', 'CENTENKA.NS', 'CCHHL.NS', 'CASTEXTECH.NS', 'HITECHCORP.NS', 'HITECHGEAR.NS', 'CANTABIL.NS', 'BSL.NS', 'BYKE.NS', 'CELEBRITY.NS', 'COFFEEDAY.NS', 'GTNTEX.NS', 'FEL.NS', 'GOENKA.NS', 'COX&KINGS.NS', 'CORALFINAC.NS', 'HINDNATGLS.NS', 'COSMOFILMS.NS', 'HINDMOTORS.NS', 'JAINSTUDIO.NS', 'JAGRAN.NS', 'RCOM.NS', 'INOXLEISUR.NS', 'SABEVENTS.NS', 'SABTN.NS', 'SAMBHAAV.NS', 'SANDESH.NS', 'SAREGAMA.NS', 'MATRIMONY.NS', 'DNAMEDIA.NS', 'SHEMAROO.NS', 'DISHTV.NS', 'IMAGICAA.NS', 'HTMEDIA.NS', 'SILLYMONKS.NS', 'DGCONTENT.NS', 'SITINET.NS', 'ENIL.NS', 'SCHAND.NS', 'RAJTV.NS', 'EROSMEDIA.NS', 'NAVNETEDUL.NS', 'NDTV.NS', 'NETWORK18.NS', 'NEXTMEDIA.NS', 'DEN.NS', 'NXTDIGITAL.NS', 'ONMOBILE.NS', 'GFLLIMITED.NS', 'GTL.NS', 'ORTEL.NS', 'GTPL.NS', 'PFOCUS.NS', 'PNC.NS', 'MUKTAARTS.NS', 'JUSTDIAL.NS', 'PRESSMN.NS', 'MTNL.NS', 'BALAJITELE.NS', 'HATHWAY.NS', 'MPSLTD.NS', 'BCG.NS', 'RADAAN.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'BAGFILMS.NS', 'HMVL.NS', 'DALALSTCOM.NS', 'UFO.NS', 'CYBERMEDIA.NS', 'TIPSINDLTD.NS', 'DBCORP.NS', 'TVVISION.NS', 'TOUCHWOOD.NS', 'TVTODAY.NS', 'ZEEMEDIA.NS', 'CINEVISTA.NS', 'VERTOZ.NS', 'CREATIVEYE.NS', 'TTML.NS', 'VALIANTORG.NS', 'JKLAKSHMI.NS', 'GSFC.NS', 'SUDARSCHEM.NS', 'RCF.NS', 'JSL.NS', 'TATASTLLP.NS', 'RESPONIND.NS', 'MOIL.NS', 'DHANUKA.NS', 'STARCEMENT.NS', 'PRIVISCL.NS', 'JSLHISAR.NS', 'MIDHANI.NS', 'WELCORP.NS', 'GULFOILLUB.NS', 'PHILIPCARB.NS', 'MEGH.NS', 'JINDALPOLY.NS', 'POLYPLEX.NS', 'NFL.NS', 'GPIL.NS', 'NOCIL.NS', 'TATAMETALI.NS', 'GUJALKALI.NS', 'SHARDACROP.NS', 'HERANBA.NS', 'JSWISPL.NS', 'DEEPAKFERT.NS', 'JINDALSAW.NS', 'OAL.NS', 'BEPL.NS', 'ASTEC.NS', 'JKPAPER.NS', 'GREENPLY.NS', 'ORIENTCEM.NS', 'GHCL.NS', 'SURYAROSNI.NS', 'MAITHANALL.NS', 'INEOSSTYRO.NS', 'CAMLINFINE.NS', 'TINPLATE.NS', 'HSCL.NS', 'NEOGEN.NS', 'MAHSEAMLES.NS', 'SARDAEN.NS', 'SAGCEM.NS', 'TIDEWATER.NS', 'JAICORPLTD.NS', 'MUKANDLTD.NS', 'CHEMCON.NS', 'APCOTEXIND.NS', 'PRAKASH.NS', 'KIRIINDUS.NS', 'USHAMART.NS', 'KSL.NS', 'ORISSAMINE.NS', 'INDIAGLYCO.NS', 'GALLISPAT.NS', 'SOTL.NS', 'SUNFLAG.NS', 'IGPL.NS', 'PUNJABCHEM.NS', 'KCP.NS', 'MANALIPETC.NS', 'ELECTCAST.NS', 'EXCELINDUS.NS', 'ASHAPURMIN.NS', 'WSTCSTPAPR.NS', 'IFGLEXPOR.NS', 'KESORAMIND.NS', 'ESTER.NS', 'JAYNECOIND.NS', 'BODALCHEM.NS', 'SANGHIIND.NS', 'IMFA.NS', 'MANGCHEFER.NS', 'ANDHRSUGAR.NS', 'AARTISURF.NS', 'INSECTICID.NS', 'CLNINDIA.NS', 'FAIRCHEMOR.NS', 'KINGFA.NS', 'TIRUMALCHM.NS', 'SHREDIGCEM.NS', 'RAJRATAN.NS', 'NACLIND.NS', 'VIDHIING.NS', 'GOCLCORP.NS', 'SESHAPAPER.NS', 'TNPL.NS', 'OCCL.NS', 'SIRCA.NS', 'ANDHRAPAP.NS', 'FCL.NS', 'BHAGERIA.NS', 'FOSECOIND.NS', 'DCW.NS', 'NCLIND.NS', 'SPIC.NS', 'SATIA.NS', 'NATHBIOGEN.NS', 'AVTNPL.NS', 'TNPETRO.NS', 'VSSL.NS', 'MANGLMCEM.NS', 'SALASAR.NS', 'GULPOLY.NS', 'UNIENTER.NS', 'PLASTIBLEN.NS', 'DECCANCE.NS', 'BESTAGRO.NS', 'KUANTUM.NS', 'APCL.NS', 'DYNPRO.NS', 'KANORICHEM.NS', 'MANINDS.NS', 'JAIBALAJI.NS', 'ORIENTPPR.NS', 'JAYAGROGN.NS', 'SHREEPUSHK.NS', 'GALLANTT.NS', 'STEELXIND.NS', 'SHALPAINTS.NS', 'NAGAFERT.NS', 'SRHHYPOLTD.NS', 'JUBLINDS.NS', 'MADRASFERT.NS', 'ASAHISONG.NS', 'MSPL.NS', 'ZUARI.NS', 'KAMDHENU.NS', 'NRAIL.NS', 'HITECH.NS', 'VISHNU.NS', 'BHARATWIRE.NS', 'DICIND.NS', 'GSCLCEMENT.NS', 'CHEMBOND.NS', 'ORIENTABRA.NS', 'GOACARBON.NS', 'VINYLINDIA.NS', 'ISMTLTD.NS', 'MCL.NS', 'PODDARMENT.NS', 'RAMANEWS.NS', 'AKSHARCHEM.NS', 'MMP.NS', 'KOTHARIPET.NS', 'AGARIND.NS', 'PDMJEPAPER.NS', 'ARVEE.NS', 'KRISHANA.NS', 'CHEMFAB.NS', 'GENUSPAPER.NS', 'STARPAPER.NS', 'SHYAMCENT.NS', 'ASTRON.NS', 'KAKATCEM.NS', 'MBAPL.NS', 'ANDHRACEMT.NS', 'MANAKSTEEL.NS', 'BALLARPUR.NS', 'BHAGYANGR.NS', '20MICRONS.NS', 'PREMEXPLN.NS', 'BSHSL.NS', 'RUCHIRA.NS', 'JOCIL.NS', 'ARIES.NS', 'SEYAIND.NS', 'ADHUNIKIND.NS', 'MAHASTEEL.NS', 'MAANALU.NS', 'XPROINDIA.NS', 'RAMASTEEL.NS', 'SHREYANIND.NS', 'VISASTEEL.NS', 'UTTAMSTL.NS', 'IVP.NS', 'SHRENIK.NS', 'VIKASWSP.NS', 'RAJMET.NS', 'VIKASPROP.NS', 'SIGIND.NS', 'MANAKALUCO.NS', 'PREMIERPOL.NS', 'SICAGEN.NS', 'BEDMUTHA.NS', 'ABMINTLTD.NS', 'SAGARDEEP.NS', 'VIKASECO.NS', 'ARCHIDPLY.NS', 'SUPREMEENG.NS', 'TAINWALCHM.NS', 'HISARMETAL.NS', 'ALKALI.NS', 'SUNDARAM.NS', 'CENTEXT.NS', 'WIPL.NS', 'GAL.NS', 'MALUPAPER.NS', 'CUBEXTUB.NS', 'BVCL.NS', 'VASWANI.NS', 'SALSTEEL.NS', 'SANGINITA.NS', 'KRIDHANINF.NS', 'ROHITFERRO.NS', 'AGROPHOS.NS', 'NATNLSTEEL.NS', 'BURNPUR.NS', 'PRAKASHSTL.NS', 'SEPOWER.NS', 'MANGTIMBER.NS', 'ANKITMETAL.NS', 'MAGNUM.NS', 'ZENITHSTL.NS', 'JIYAECO.NS', 'IMPEXFERRO.NS', 'SMPL.NS', 'GFSTEELS.NS', 'NTL.NS', 'ARENTERP.NS']
    util_lc = ['TORNTPOWER.NS', 'IGL.NS', 'ATGL.NS', 'GAIL.NS', 'ADANIPOWER.NS', 'TATAPOWER.NS', 'NHPC.NS', 'ADANIGREEN.NS', 'GUJGASLTD.NS', 'ADANITRANS.NS', 'POWERGRID.NS', 'NTPC.NS'] 
    ind_lc = ['3MINDIA.NS', 'ABB.NS', 'HONAUT.NS', 'VOLTAS.NS', 'CONCOR.NS', 'INDIGO.NS', 'CUMMINSIND.NS', 'SIEMENS.NS', 'ADANIPORTS.NS', 'ASTRAL.NS', 'BHEL.NS', 'LT.NS', 'HAL.NS', 'HAVELLS.NS', 'POLYCAB.NS', 'BEL.NS', 'IRCTC.NS']
    re_lc = ['LODHA.NS', 'GODREJPROP.NS', 'DLF.NS']
    tech_lc = ['LTTS.NS', 'VAKRANGEE.NS', 'MASTEK.NS', 'WIPRO.NS', 'KPITTECH.NS', 'LTI.NS', 'WHIRLPOOL.NS', 'MINDTREE.NS', 'ZENSARTECH.NS', 'BSOFT.NS', 'AMBER.NS', 'IFBIND.NS', 'SONATSOFTW.NS', 'POWERINDIA.NS', 'JCHAC.NS', 'PERSISTENT.NS', 'HCLTECH.NS', 'STLTECH.NS', 'SUBEXLTD.NS', 'HAPPSTMNDS.NS', 'AGCNET.NS', 'FSL.NS', 'INFIBEAM.NS', 'ECLERX.NS', 'INTELLECT.NS', 'ITI.NS', 'HFCL.NS', 'REDINGTON.NS', 'DIXON.NS', 'INFY.NS', 'NEWGEN.NS', 'TCS.NS', 'TECHM.NS', 'COFORGE.NS', 'MPHASIS.NS', 'TATAELXSI.NS', 'SWSOLAR.NS', 'TANLA.NS', 'OFSS.NS']
    health_lc = ['SUNPHARMA.NS', 'DRREDDY.NS', 'APOLLOHOSP.NS', 'DIVISLAB.NS', 'BIOCON.NS', 'PFIZER.NS', 'ALKEM.NS', 'IPCALAB.NS', 'GLAXO.NS', 'GLAND.NS', 'CIPLA.NS', 'TORNTPHARM.NS', 'LUPIN.NS', 'MAXHEALTH.NS', 'ABBOTINDIA.NS', 'AUROPHARMA.NS', 'LALPATHLAB.NS', 'LAURUSLABS.NS', 'CADILAHC.NS', 'SYNGENE.NS']
    fs_lc = ['BAJFINANCE.NS', 'SUNDARMFIN.NS', 'PNB.NS', 'IDBI.NS', 'HDFCLIFE.NS', 'MFSL.NS', 'CHOLAFIN.NS', 'IDFCFIRSTB.NS', 'BAJAJHLDNG.NS', 'GICRE.NS', 'PFC.NS', 'PEL.NS', 'SRTRANSFIN.NS', 'NIACL.NS', 'MUTHOOTFIN.NS', 'HDFCBANK.NS', 'HDFCAMC.NS', 'NAM-INDIA.NS', 'HDFC.NS', 'BANDHANBNK.NS', 'UNIONBANK.NS', 'BANKBARODA.NS', 'RECLTD.NS', 'AUBANK.NS', 'IRFC.NS', 'L&TFH.NS', 'BANKINDIA.NS', 'CANBK.NS', 'KOTAKBANK.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SBIN.NS', 'LICHSGFIN.NS', 'ICICIPRULI.NS', 'INDUSINDBK.NS', 'BAJAJFINSV.NS', 'IOB.NS', 'ICICIGI.NS', 'ICICIBANK.NS', 'YESBANK.NS', 'AXISBANK.NS', 'ABCAPITAL.NS']
    eng_lc = ['ADANIENT.NS', 'ONGC.NS', 'PETRONET.NS', 'RELIANCE.NS', 'COALINDIA.NS', 'BPCL.NS', 'HINDPETRO.NS', 'IOC.NS']
    cd_lc = ['MCDOWELL-N.NS', 'PGHH.NS', 'NESTLEIND.NS', 'GODREJCP.NS', 'MARICO.NS', 'RUCHI.NS', 'DABUR.NS', 'TATACONSUM.NS', 'COLPAL.NS', 'BRITANNIA.NS', 'VBL.NS', 'UBL.NS', 'EMAMILTD.NS', 'DMART.NS', 'ITC.NS', 'HINDUNILVR.NS']
    cc_lc =['MARUTI.NS', 'M&M.NS', 'TVSMOTOR.NS', 'MRF.NS', 'MOTHERSUMI.NS', 'ASHOKLEY.NS', 'BAJAJ-AUTO.NS', 'JUBLFOOD.NS', 'BALKRISIND.NS', 'RELAXO.NS', 'SUPREMEIND.NS', 'PAGEIND.NS', 'TIINDIA.NS', 'TITAN.NS', 'TRENT.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'BHARATFORG.NS', 'BOSCHLTD.NS', 'HEROMOTOCO.NS', 'EICHERMOT.NS', 'CROMPTON.NS']
    cs_lc =['INDUSTOWER.NS', 'NAUKRI.NS', 'INDIAMART.NS', 'IDEA.NS', 'BHARTIARTL.NS', 'SUNTV.NS', 'TATACOMM.NS']
    bm_lc =['ASIANPAINT.NS', 'ULTRACEMCO.NS', 'JSWSTEEL.NS', 'HINDZINC.NS', 'TATASTEEL.NS', 'VEDL.NS', 'SHREECEM.NS', 'PIDILITIND.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BERGEPAINT.NS', 'AMBUJACEM.NS', 'UPL.NS', 'NMDC.NS', 'SAIL.NS', 'JINDALSTEL.NS', 'PIIND.NS', 'SRF.NS', 'ACC.NS', 'DALBHARAT.NS', 'KANSAINER.NS', 'AARTIIND.NS', 'BAYERCROP.NS', 'ATUL.NS', 'DEEPAKNTR.NS', 'COROMANDEL.NS', 'RAMCOCEM.NS', 'JKCEMENT.NS']
    util_mc=['BAJAJELEC.NS', 'MGL.NS', 'JSWENERGY.NS', 'CESC.NS', 'SJVN.NS', 'NLCINDIA.NS', 'GSPL.NS']
   
    tech_mc=['VAKRANGEE.NS', 'KPITTECH.NS', 'ZENSARTECH.NS', 'BSOFT.NS', 'AMBER.NS', 'SONATSOFTW.NS', 'POWERINDIA.NS', 'JCHAC.NS', 'PERSISTENT.NS', 'STLTECH.NS', 'HAPPSTMNDS.NS', 'FSL.NS', 'INFIBEAM.NS', 'INTELLECT.NS', 'ITI.NS', 'REDINGTON.NS', 'TANLA.NS']
   
    re_mc =['BRIGADE.NS', 'PRESTIGE.NS', 'PHOENIXLTD.NS', 'OBEROIRLTY.NS']
   
    ind_mc=['VGUARD.NS', 'SCHAEFFLER.NS', 'SCI.NS', 'CARBORUNIV.NS', 'TEAMLEASE.NS', 'AIAENG.NS', 'THERMAX.NS', 'SUZLON.NS', 'CYIENT.NS', 'DBL.NS', 'TIMKEN.NS', 'SKFINDIA.NS', 'SIS.NS', 'CERA.NS', 'BLUEDART.NS', 'COCHINSHIP.NS', 'BDL.NS', 'BBTC.NS', 'BLUESTARCO.NS', 'CGPOWER.NS', 'PNCINFRA.NS', 'FINCABLES.NS', 'FINPIPE.NS', 'KALPATPOWR.NS', 'GESHIP.NS', 'BEML.NS', 'GMRINFRA.NS', 'MMTC.NS', 'GODREJIND.NS', 'KAJARIACER.NS', 'NBCC.NS', 'GMMPFAUDLR.NS', 'KNRCON.NS', 'ESCORTS.NS', 'LAXMIMACH.NS', 'QUESS.NS', 'HEG.NS', 'RITES.NS', 'KEC.NS', 'ELGIEQUIP.NS', 'GRINDWELL.NS', 'RVNL.NS', 'PRAJIND.NS', 'GRAPHITE.NS']
    
    health_mc=['FORTIS.NS', 'ORCHPHARMA.NS', 'ERIS.NS', 'APLLTD.NS', 'SOLARA.NS', 'AJANTPHARM.NS', 'JBCHEPHARM.NS', 'SPARC.NS', 'STAR.NS', 'SANOFI.NS', 'SEQUENT.NS', 'PGHL.NS', 'FDC.NS', 'POLYMED.NS', 'GLENMARK.NS', 'GRANULES.NS', 'AARTIDRUGS.NS', 'NATCOPHARM.NS', 'THYROCARE.NS', 'ASTERDM.NS', 'ASTRAZEN.NS', 'METROPOLIS.NS', 'JUBLPHARMA.NS', 'JUBLINGREA.NS', 'WOCKPHARMA.NS', 'NH.NS', 'SUVENPHAR.NS']
   
    fs_mc=['CHOLAHLDNG.NS', 'CREDITACC.NS', 'PNBHOUSING.NS', 'MOTILALOFS.NS', 'CRISIL.NS', 'MCX.NS', 'CUB.NS', 'IDFC.NS', 'UJJIVANSFB.NS', 'UCOBANK.NS', 'IEX.NS', 'INDIANB.NS', 'TATAINVEST.NS', 'JMFINANCIL.NS', 'IIFLWAM.NS', 'IIFL.NS', 'FEDERALBNK.NS', 'M&MFIN.NS', 'HUDCO.NS', 'CDSL.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'ISEC.NS', 'CAMS.NS', 'AAVAS.NS', 'CENTRALBK.NS', 'SHRIRAMCIT.NS', 'DHANI.NS', 'UTIAMC.NS', 'PSB.NS', 'EDELWEISS.NS', 'ANGELBRKG.NS', 'IBULHSGFIN.NS', 'CANFINHOME.NS', 'EQUITASBNK.NS', 'MANAPPURAM.NS']
  
    eng_mc=['MRPL.NS', 'OIL.NS', 'AEGISCHEM.NS']
   
    cd_mc=['AVANTIFEED.NS', 'KRBL.NS', 'GILLETTE.NS', 'GODREJAGRO.NS', 'RADICO.NS', 'EIDPARRY.NS', 'ZYDUSWELL.NS', 'JYOTHYLAB.NS', 'HATSUN.NS', 'BALRAMCHIN.NS']
    
    cc_mc=['LUXIND.NS', 'VARROC.NS', 'MAHINDCIE.NS', 'MINDAIND.NS', 'ABFRL.NS', 'WELSPUNIND.NS', 'WESTLIFE.NS', 'INDHOTEL.NS', 'BATAINDIA.NS', 'KALYANKJIL.NS', 'VMART.NS', 'VTL.NS', 'WABCOINDIA.NS', 'KPRMILL.NS', 'TRIDENT.NS', 'SUNDRMFAST.NS', 'ALOKINDS.NS', 'AMARAJABAT.NS', 'SFL.NS', 'SUNCLAYLTD.NS', 'ORIENTELEC.NS', 'TTKPRESTIG.NS', 'ASAHIINDIA.NS', 'RAJESHEXPO.NS', 'SYMPHONY.NS', 'APOLLOTYRE.NS', 'GARFIBRES.NS', 'EXIDEIND.NS', 'EPL.NS', 'ENDURANCE.NS', 'EIHOTEL.NS', 'CENTURYPLY.NS', 'CEATLTD.NS']
    
    cs_mc = ['JAINSTUDIO.NS', 'JAGRAN.NS', 'RCOM.NS', 'INOXLEISUR.NS', 'ROUTE.NS', 'SABEVENTS.NS', 'SABTN.NS', 'INDUSTOWER.NS', 'SAMBHAAV.NS', 'SANDESH.NS', 'SAREGAMA.NS', 'NAUKRI.NS', 'INDIAMART.NS', 'MATRIMONY.NS', 'DNAMEDIA.NS', 'SHEMAROO.NS', 'DISHTV.NS', 'IMAGICAA.NS', 'IDEA.NS', 'HTMEDIA.NS', 'SILLYMONKS.NS', 'DGCONTENT.NS', 'SITINET.NS', 'ENIL.NS', 'SCHAND.NS', 'RAJTV.NS', 'EROSMEDIA.NS', 'NAVNETEDUL.NS', 'NAZARA.NS', 'NDTV.NS', 'NETWORK18.NS', 'NEXTMEDIA.NS', 'DEN.NS', 'BHARTIARTL.NS', 'NXTDIGITAL.NS', 'ONMOBILE.NS', 'GFLLIMITED.NS', 'GTL.NS', 'ORTEL.NS', 'GTPL.NS', 'PFOCUS.NS', 'PNC.NS', 'MUKTAARTS.NS', 'JUSTDIAL.NS', 'PRESSMN.NS', 'MTNL.NS', 'BALAJITELE.NS', 'HATHWAY.NS', 'MPSLTD.NS', 'BCG.NS', 'RADAAN.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'BAGFILMS.NS', 'PVR.NS', 'HMVL.NS', 'TV18BRDCST.NS', 'DALALSTCOM.NS', 'UFO.NS', 'CYBERMEDIA.NS', 'TIPSINDLTD.NS', 'DBCORP.NS', 'SUNTV.NS', 'TATACOMM.NS', 'TVVISION.NS', 'ZEEL.NS', 'TOUCHWOOD.NS', 'AFFLE.NS', 'TVTODAY.NS', 'ZEEMEDIA.NS', 'CINEVISTA.NS', 'VERTOZ.NS', 'CREATIVEYE.NS', 'TTML.NS']
   
    bm_mc = ['ASIANPAINT.NS', 'ULTRACEMCO.NS', 'JSWSTEEL.NS', 'HINDZINC.NS', 'TATASTEEL.NS', 'VEDL.NS', 'SHREECEM.NS', 'PIDILITIND.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BERGEPAINT.NS', 'AMBUJACEM.NS', 'UPL.NS', 'NMDC.NS', 'SAIL.NS', 'JINDALSTEL.NS', 'PIIND.NS', 'SRF.NS', 'ACC.NS', 'DALBHARAT.NS', 'KANSAINER.NS', 'AARTIIND.NS', 'BAYERCROP.NS', 'ATUL.NS', 'DEEPAKNTR.NS', 'COROMANDEL.NS', 'RAMCOCEM.NS', 'JKCEMENT.NS', 'TATACHEM.NS', 'VINATIORGA.NS', 'HINDCOPPER.NS', 'NAVINFLUOR.NS', 'SUMICHEM.NS', 'APLAPOLLO.NS', 'LINDEINDIA.NS', 'NATIONALUM.NS', 'CASTROLIND.NS', 'KIOCL.NS', 'INDIGOPNTS.NS', 'CHAMBLFERT.NS', 'SOLARINDS.NS', 'BASF.NS', 'TATASTLBSL.NS', 'DCMSHRIRAM.NS', 'GALAXYSURF.NS', 'AKZOINDIA.NS', 'FINEORG.NS', 'FLUOROCHEM.NS', 'RATNAMANI.NS', 'FACT.NS', 'BIRLACORPN.NS', 'BALAMINES.NS', 'ALKYLAMINE.NS', 'ANURAS.NS', 'ROSSARI.NS', 'PRSMJOHNSN.NS', 'PRINCEPIPE.NS', 'SUPPETRO.NS', 'GNFC.NS', 'RALLIS.NS', 'LXCHEM.NS', 'RAIN.NS', 'BHARATRAS.NS', 'CENTURYTEX.NS', 'INDIACEM.NS', 'HEIDELBERG.NS', 'ADVENZYMES.NS', 'VALIANTORG.NS', 'JKLAKSHMI.NS', 'GSFC.NS', 'SUDARSCHEM.NS', 'RCF.NS', 'JSL.NS', 'TATASTLLP.NS', 'RESPONIND.NS', 'MOIL.NS', 'DHANUKA.NS', 'STARCEMENT.NS', 'PRIVISCL.NS', 'JSLHISAR.NS', 'MIDHANI.NS', 'WELCORP.NS', 'GULFOILLUB.NS', 'PHILIPCARB.NS', 'MEGH.NS', 'JINDALPOLY.NS', 'POLYPLEX.NS', 'NFL.NS', 'GPIL.NS', 'NOCIL.NS', 'TATAMETALI.NS', 'GUJALKALI.NS', 'SHARDACROP.NS', 'HERANBA.NS', 'JSWISPL.NS', 'DEEPAKFERT.NS', 'JINDALSAW.NS', 'OAL.NS', 'BEPL.NS', 'ASTEC.NS', 'JKPAPER.NS', 'GREENPLY.NS', 'ORIENTCEM.NS', 'GHCL.NS', 'SURYAROSNI.NS', 'MAITHANALL.NS', 'INEOSSTYRO.NS', 'CAMLINFINE.NS', 'TINPLATE.NS', 'HSCL.NS', 'NEOGEN.NS', 'MAHSEAMLES.NS', 'SARDAEN.NS', 'SAGCEM.NS', 'TIDEWATER.NS', 'JAICORPLTD.NS', 'MUKANDLTD.NS', 'CHEMCON.NS', 'APCOTEXIND.NS', 'PRAKASH.NS', 'KIRIINDUS.NS', 'USHAMART.NS', 'KSL.NS', 'ORISSAMINE.NS', 'INDIAGLYCO.NS', 'GALLISPAT.NS', 'SOTL.NS', 'SUNFLAG.NS', 'IGPL.NS', 'PUNJABCHEM.NS', 'KCP.NS', 'MANALIPETC.NS', 'ELECTCAST.NS', 'EXCELINDUS.NS', 'ASHAPURMIN.NS', 'WSTCSTPAPR.NS', 'IFGLEXPOR.NS', 'KESORAMIND.NS', 'ESTER.NS', 'JAYNECOIND.NS', 'BODALCHEM.NS', 'SANGHIIND.NS', 'IMFA.NS', 'MANGCHEFER.NS', 'ANDHRSUGAR.NS', 'AARTISURF.NS', 'INSECTICID.NS', 'CLNINDIA.NS', 'FAIRCHEMOR.NS', 'KINGFA.NS', 'TIRUMALCHM.NS', 'SHREDIGCEM.NS', 'RAJRATAN.NS', 'NACLIND.NS', 'VIDHIING.NS', 'GOCLCORP.NS', 'SESHAPAPER.NS', 'TNPL.NS', 'OCCL.NS', 'SIRCA.NS', 'ANDHRAPAP.NS', 'FCL.NS', 'BHAGERIA.NS', 'FOSECOIND.NS', 'DCW.NS', 'NCLIND.NS', 'SPIC.NS', 'SATIA.NS', 'NATHBIOGEN.NS', 'AVTNPL.NS', 'TNPETRO.NS', 'VSSL.NS', 'MANGLMCEM.NS', 'SALASAR.NS', 'GULPOLY.NS', 'UNIENTER.NS', 'PLASTIBLEN.NS', 'DECCANCE.NS', 'BESTAGRO.NS', 'KUANTUM.NS', 'APCL.NS', 'DYNPRO.NS', 'KANORICHEM.NS', 'MANINDS.NS', 'JAIBALAJI.NS', 'ORIENTPPR.NS', 'JAYAGROGN.NS', 'SHREEPUSHK.NS', 'GALLANTT.NS', 'STEELXIND.NS', 'SHALPAINTS.NS', 'NAGAFERT.NS', 'SRHHYPOLTD.NS', 'JUBLINDS.NS', 'MADRASFERT.NS', 'ASAHISONG.NS', 'MSPL.NS', 'ZUARI.NS', 'KAMDHENU.NS', 'NRAIL.NS', 'HITECH.NS', 'VISHNU.NS', 'BHARATWIRE.NS', 'DICIND.NS', 'GSCLCEMENT.NS', 'CHEMBOND.NS', 'ORIENTABRA.NS', 'GOACARBON.NS', 'VINYLINDIA.NS', 'ISMTLTD.NS', 'MCL.NS', 'PODDARMENT.NS', 'RAMANEWS.NS', 'AKSHARCHEM.NS', 'MMP.NS', 'KOTHARIPET.NS', 'AGARIND.NS', 'PDMJEPAPER.NS', 'ARVEE.NS', 'KRISHANA.NS', 'CHEMFAB.NS', 'GENUSPAPER.NS', 'STARPAPER.NS', 'SHYAMCENT.NS', 'ASTRON.NS', 'KAKATCEM.NS', 'MBAPL.NS', 'ANDHRACEMT.NS', 'MANAKSTEEL.NS', 'BALLARPUR.NS', 'BHAGYANGR.NS', '20MICRONS.NS', 'PREMEXPLN.NS', 'BSHSL.NS', 'RUCHIRA.NS', 'JOCIL.NS', 'ARIES.NS', 'SEYAIND.NS', 'ADHUNIKIND.NS', 'MAHASTEEL.NS', 'MAANALU.NS', 'XPROINDIA.NS', 'RAMASTEEL.NS', 'SHREYANIND.NS', 'VISASTEEL.NS', 'UTTAMSTL.NS', 'IVP.NS', 'SHRENIK.NS', 'VIKASWSP.NS', 'RAJMET.NS', 'VIKASPROP.NS', 'SIGIND.NS', 'MANAKALUCO.NS', 'PREMIERPOL.NS', 'SICAGEN.NS', 'BEDMUTHA.NS', 'ABMINTLTD.NS', 'SAGARDEEP.NS', 'VIKASECO.NS', 'ARCHIDPLY.NS', 'SUPREMEENG.NS', 'TAINWALCHM.NS', 'HISARMETAL.NS', 'ALKALI.NS', 'SUNDARAM.NS', 'CENTEXT.NS', 'WIPL.NS', 'GAL.NS', 'MALUPAPER.NS', 'CUBEXTUB.NS', 'BVCL.NS', 'VASWANI.NS', 'SALSTEEL.NS', 'SANGINITA.NS', 'KRIDHANINF.NS', 'ROHITFERRO.NS', 'AGROPHOS.NS', 'NATNLSTEEL.NS', 'BURNPUR.NS', 'PRAKASHSTL.NS', 'SEPOWER.NS', 'MANGTIMBER.NS', 'ANKITMETAL.NS', 'MAGNUM.NS', 'ZENITHSTL.NS', 'JIYAECO.NS', 'IMPEXFERRO.NS', 'SMPL.NS', 'GFSTEELS.NS', 'NTL.NS', 'ARENTERP.NS']
     
    util_sc =['RTNINDIA.NS', 'RPOWER.NS', 'RTNPOWER.NS', 'DPSCLTD.NS', 'RELINFRA.NS', 'GIPCL.NS', 'INDOWIND.NS', 'KARMAENG.NS', 'PTC.NS', 'GREENPOWER.NS', 'NBVENTURES.NS', 'ENERGYDEV.NS', 'JPPOWER.NS', 'SURANAT&P.NS']

    tech_sc = ['MIC.NS', 'UJAAS.NS', 'CENTUM.NS', 'MINDTECK.NS', 'XCHANGING.NS', 'KELLTONTEC.NS', '3IINFOTECH.NS', 'MASTEK.NS', 'XELPMOC.NS', 'AURIONPRO.NS', 'GTLINFRA.NS', 'ACCELYA.NS', 'MAJESCO.NS', 'GSS.NS', 'WEBELSOLAR.NS', 'ASTRAMICRO.NS', 'CEREBRAINT.NS', 'JUMPNET.NS', 'GOLDTECH.NS', 'MEGASOFT.NS', 'MELSTAR.NS', 'URJA.NS', 'CALSOFT.NS', 'HOVS.NS', 'IFBIND.NS', 'EXPLEOSOL.NS', 'BIRLACABLE.NS', 'FCSSOFT.NS', 'AIRAN.NS', 'PGEL.NS', 'SMARTLINK.NS', 'PARACABLES.NS', 'PALREDTEC.NS', 'HCL-INSYS.NS', 'SUBEXLTD.NS', 'DATAMATICS.NS', 'AGCNET.NS', 'BARTRONICS.NS', 'CYBERTECH.NS', 'PANACHE.NS', 'QUICKHEAL.NS', 'INFOBEAN.NS', 'ECLERX.NS', 'INTENTECH.NS', 'DSSL.NS', 'RSYSTEMS.NS', 'RSSOFTWARE.NS', 'SASKEN.NS', 'ROLTA.NS', 'DRCSYSTEMS.NS', 'INSPIRISYS.NS', 'SECURKLOUD.NS', 'HFCL.NS', 'IZMO.NS', 'DLINKINDIA.NS', 'DIGISPICE.NS', 'RAMCOSYS.NS', 'ALANKIT.NS', 'AKSHOPTFBR.NS', 'SHYAMTEL.NS', 'OPTIEMUS.NS', 'ONWARDTEC.NS', 'INDOSOLAR.NS', 'TEJASNET.NS', 'BPL.NS', 'NEWGEN.NS', 'SURANASOL.NS', 'NELCO.NS', 'TERASOFT.NS', 'COMPINFO.NS', 'GENESYS.NS', 'TNTELE.NS', 'MRO-TEK.NS', 'TREJHARA.NS', 'TRIGYN.NS', 'CIGNITITEC.NS', 'TVSELECT.NS', 'SAKSOFT.NS', 'KERNEX.NS', 'SWELECTES.NS', 'SWSOLAR.NS', 'NUCLEUS.NS', 'CREATIVE.NS', 'SUVIDHAA.NS', 'ADSL.NS', 'ADROITINFO.NS', 'CTE.NS']

    re_sc = ['KOLTEPATIL.NS', 'TECHIN.NS', 'EMAMIREAL.NS', 'TCIDEVELOP.NS', 'CINELINE.NS', 'MODIRUBBER.NS', 'TEXINFRA.NS', 'RVHL.NS', 'MOTOGENFIN.NS', 'ARVSMART.NS', 'GEECEE.NS', 'BHAGYAPROP.NS', 'UNITECH.NS', 'ASHIANA.NS', 'AMJLAND.NS', 'ANANTRAJ.NS', 'COUNCODOS.NS', 'DBREALTY.NS', 'NILASPACES.NS', 'ARIHANTSUP.NS', 'SUNTECK.NS', 'PTL.NS', 'ARIHANT.NS', 'NILAINFRA.NS', 'FMNL.NS', 'SUMIT.NS', 'OSWALAGRO.NS', 'VIPULLTD.NS', 'HUBTOWN.NS', 'KARDA.NS', 'HDIL.NS', 'PARSVNATH.NS', 'PENINLAND.NS', 'SOBHA.NS', 'AJMERA.NS', 'PRAENG.NS', 'LPDC.NS', 'BOMDYEING.NS', 'PODDARHOUS.NS', 'MAHLIFE.NS', 'OMAXE.NS', 'PROZONINTU.NS', 'IBREALEST.NS', 'TARC.NS', 'BSELINFRA.NS', 'SHRADHA.NS', 'ANSALAPI.NS', 'ANSALHSG.NS', 'HEMIPROP.NS', 'MARATHON.NS', 'GANESHHOUC.NS']

    ind_sc = ['INGERRAND.NS', 'VINDHYATEL.NS', 'VISAKAIND.NS', 'AARVI.NS', 'CEBBCO.NS', 'SALZERELEC.NS', 'ZENTEC.NS', 'SHANTIGEAR.NS', 'BLS.NS', 'ALICON.NS', 'VETO.NS', 'VESUVIUS.NS', 'BLKASHYAP.NS', 'ICEMAKE.NS', 'SHREYAS.NS', 'VASCONEQ.NS', 'SANCO.NS', 'CAPACITE.NS', 'WALCHANNAG.NS', 'AARON.NS', 'WELENT.NS', 'WABAG.NS', 'SCHNEIDER.NS', 'VSTTILLERS.NS', 'SEAMECLTD.NS', 'DREDGECORP.NS', 'HONDAPOWER.NS', 'ALLSEC.NS', 'WENDT.NS', 'ALLCARGO.NS', 'DPWIRES.NS', 'SETUINFRA.NS', 'VRLLOG.NS', 'CANDC.NS', 'INOXWIND.NS', 'SHAKTIPUMP.NS', 'VOLTAMP.NS', 'WINDMACHIN.NS', 'HPL.NS', 'WSI.NS', 'SANGHVIMOV.NS', 'HLEGLAS.NS', 'DUCON.NS', 'CCCL.NS', 'A2ZINFRA.NS', 'ACCURACY.NS', 'SICAL.NS', 'TCI.NS', 'TCIEXP.NS', 'TDPOWERSYS.NS', 'INDOTECH.NS', 'SRIPIPES.NS', 'TECHNOE.NS', 'AHLUCONT.NS', 'TEXMOPIPES.NS', 'TEXRAIL.NS', 'DCM.NS', 'TIIL.NS', 'TIJARIA.NS', 'TEMBO.NS', 'CONTROLPR.NS', 'STCINDIA.NS', 'IL&FSTRANS.NS', 'INDIANHUME.NS', 'INDLMETER.NS', 'SUNDARMHLD.NS', 'HILTON.NS', 'BEARDSELL.NS', 'TANTIACONS.NS', 'HIL.NS', 'STERTOOLS.NS', 'TARAPUR.NS', 'TARMAT.NS', 'AHLADA.NS', 'ADORWELD.NS', 'CORDSCABLE.NS', 'TIL.NS', 'BBL.NS', 'SPMLINFRA.NS', 'UNIVASTU.NS', 'UNIVCABLES.NS', 'SKIPPER.NS', 'SKIL.NS', 'DELTAMAGNT.NS', 'DENORA.NS', 'AKASH.NS', 'HGS.NS', 'SIMPLEXINF.NS', 'HGINFRA.NS', 'BCP.NS', 'ACE.NS', 'SHRIRAMEPC.NS', 'HIRECT.NS', 'TWL.NS', 'SPICEJET.NS', 'TIRUPATIFL.NS', 'CMICABLES.NS', 'TOTAL.NS', 'TRF.NS', 'TRIL.NS', 'TRITURBINE.NS', 'SORILINFRA.NS', 'SOMICONVEY.NS', 'BRNL.NS', 'SOMANYCERA.NS', 'SNOWMAN.NS', 'IL&FSENGG.NS', 'EKC.NS', 'NIRAJ.NS', 'MAHEPC.NS', 'BALMLAWRIE.NS', 'ONEPOINT.NS', 'MAHESHWARI.NS', 'MAHLOG.NS', 'OMINFRAL.NS', 'GUJAPOLLO.NS', 'JKIL.NS', 'AROGRANITE.NS', 'BIGBLOC.NS', 'ATLANTA.NS', 'MANAKCOAT.NS', 'MANAKSIA.NS', 'MANINFRA.NS', 'GAMMNINFRA.NS', 'ARSHIYA.NS', 'NOIDATOLL.NS', 'MANUGRAPH.NS', 'ARSSINFRA.NS', 'GANDHITUBE.NS', 'HCC.NS', 'MADHUCON.NS', 'ORIENTALTL.NS', 'ORIENTBELL.NS', 'MADHAV.NS', 'APOLLOPIPE.NS', 'LOKESHMACH.NS', 'PITTIENG.NS', 'LSIL.NS', 'JETAIRWAYS.NS', 'PENIND.NS', 'PDSMFL.NS', 'NITINFIRE.NS', 'PATINTLOG.NS', 'GPTINFRA.NS', 'GPPL.NS', 'GOODLUCK.NS', 'JISLDVREQS.NS', 'PAEL.NS', 'KAPSTON.NS', 'MACPOWER.NS', 'JISLJALEQS.NS', 'ORIENTREF.NS', 'JITFINFRA.NS', 'FSC.NS', 'PATELENG.NS', 'POKARNA.NS', 'MARINE.NS', 'JPINFRATEC.NS', 'GEPIL.NS', 'GET&D.NS', 'MURUDCERA.NS', 'GILLANDERS.NS', 'ASIANTILES.NS', 'MTARTECH.NS', 'MEP.NS', 'MSTCLTD.NS', 'ASHOKA.NS', 'METALFORGE.NS', 'GISOLUTION.NS', 'GKWLIMITED.NS', 'MOLDTECH.NS', 'JSWHL.NS', 'GLOBALVECT.NS', 'MODISNME.NS', 'MMFL.NS', 'GENUSPOWER.NS', 'MBLINFRA.NS', 'MBECL.NS', 'JYOTISTRUC.NS', 'NIPPOBATRY.NS', 'HBLPOWER.NS', 'NIBL.NS', 'JMCPROJECT.NS', 'GATI.NS', 'NESCO.NS', 'KABRAEXTRU.NS', 'GAYAHWS.NS', 'NITCO.NS', 'GODHA.NS', 'MAZDOCK.NS', 'NELCAST.NS', 'NECCLTD.NS', 'GAYAPROJ.NS', 'JPASSOCIAT.NS', 'GDL.NS', 'NCC.NS', 'GEEKAYWIRE.NS', 'NAVKARCORP.NS', 'GENCON.NS', 'MAZDA.NS', 'RNAVAL.NS', 'KSB.NS', 'RKEC.NS', 'LAKPRE.NS', 'KEI.NS', 'BGRENERGY.NS', 'ESABINDIA.NS', 'RKFORGE.NS', 'ELECON.NS', 'GRSE.NS', 'PURVA.NS', 'AWHCL.NS', 'KENNAMET.NS', 'ESSARSHPNG.NS', 'PUNJLLOYD.NS', 'ANUP.NS', 'EMCO.NS', 'KECL.NS', 'KOKUYOCMLN.NS', 'HERCULES.NS', 'HMT.NS', 'REPL.NS', 'REPRO.NS', 'ITDCEM.NS', 'REVATHI.NS', 'ZUARIGLOB.NS', 'RAMCOIND.NS', 'ENGINERSIN.NS', 'BANKA.NS', 'ELECTHERM.NS', 'RIIL.NS', 'RAMKY.NS', 'JASH.NS', 'KOTHARIPRO.NS', 'KIRLOSIND.NS', 'EASUNREYRL.NS', 'IRCON.NS', 'PREMIER.NS', 'PRECWIRE.NS', 'ROLLT.NS', 'GREAVESCOT.NS', 'GRAVITA.NS', 'APOLLO.NS', 'S&SPOWER.NS', 'SADBHAV.NS', 'LINCPEN.NS', 'PPL.NS', 'BFUTILITIE.NS', 'LGBFORGE.NS', 'AXISCADES.NS', 'PSPPROJECT.NS', 'APARINDS.NS', 'EIMCOELECO.NS', 'KIRLOSENG.NS', 'RPPINFRA.NS', 'IRB.NS', 'KAUSHALYA.NS', 'EVEREADY.NS', 'EVERESTIND.NS', 'KIRLFER.NS', 'POWERMECH.NS', 'EXCEL.NS', 'KIRLOSBROS.NS', 'SADBHIN.NS']

    health_sc = ['PANACEABIO.NS', 'ALPA.NS', 'ORTINLAB.NS', 'IOLCP.NS', 'HESTERBIO.NS', 'BALPHARMA.NS', 'INDOCO.NS', 'OPTOCIRCUI.NS', 'HIKAL.NS', 'INDSWFTLTD.NS', 'INDSWFTLAB.NS', 'SMSLIFE.NS', 'SMSPHARMA.NS', 'JAGSNPHARM.NS', 'ALBERTDAVD.NS', 'ALEMBICLTD.NS', 'INDRAMEDCO.NS', 'SHILPAMED.NS', 'SASTASUNDR.NS', 'DCAL.NS', 'RPGLIFE.NS', 'BIOFILCHEM.NS', 'BLISSGVS.NS', 'SHALBY.NS', 'AMRUTANJAN.NS', 'SUVEN.NS', 'MOREPENLAB.NS', 'VIVIMEDLAB.NS', 'MARKSANS.NS', 'THEMISMED.NS', 'LINCOLN.NS', 'NECLIFE.NS', 'CAPLIPOINT.NS', 'TTKHLTCARE.NS', 'BROOKS.NS', 'MAXIND.NS', 'VENUSREM.NS', 'MANGALAM.NS', 'GUFICBIO.NS', 'UNIVPHOTO.NS', 'VIMTALABS.NS', 'UNICHEMLAB.NS', 'LYKALABS.NS', 'WANBURY.NS', 'LOTUSEYE.NS', 'VAISHALI.NS', 'KREBSBIO.NS', 'KILITCH.NS', 'TAKE.NS', 'SAKAR.NS', 'NOVARTIND.NS', 'KOPRAN.NS', 'SYNCOM.NS', 'ZOTA.NS', 'HCG.NS', 'BAFNAPH.NS', 'NEULANDLAB.NS', 'LASA.NS', 'NURECA.NS']

    fs_sc = ['IFCI.NS', 'ARMANFIN.NS', 'GLFL.NS', 'SOUTHBANK.NS', 'TCIFINANCE.NS', 'SPANDANA.NS', 'PNBGILTS.NS', 'NSIL.NS', 'BINDALAGRO.NS', 'CREST.NS', 'ONELIFECAP.NS', 'UJJIVAN.NS', 'CSBBANK.NS', 'SURYODAY.NS', 'BIRLAMONEY.NS', 'SUMMITSEC.NS', 'INDOSTAR.NS', 'NBIFIN.NS', 'SREINFRA.NS', 'THEINVEST.NS', 'IITL.NS', 'STEELCITY.NS', 'NDGL.NS', 'PFS.NS', 'TFL.NS', 'TFCILTD.NS', 'DCBBANK.NS', 'DBSTOCKBRO.NS', 'CONSOFINVT.NS', 'IIFLSEC.NS', 'JINDALPHOT.NS', 'MUTHOOTCAP.NS', 'GICHSGFIN.NS', 'INDBANK.NS', 'NAGREEKCAP.NS', 'PAISALO.NS', 'INDOTHAI.NS', 'PILANIINVS.NS', 'TIMESGTY.NS', 'HBSL.NS', 'GEOJITFSL.NS', 'NAHARCAP.NS', 'DCMFINSERV.NS', 'VLSFINANCE.NS', 'REPCOHOME.NS', 'IVC.NS', 'MCDHOLDING.NS', '5PAISA.NS', 'RELIGARE.NS', 'RELCAPITAL.NS', 'CARERATING.NS', 'HEXATRADEX.NS', 'BLBLIMITED.NS', 'DOLAT.NS', 'MAGMA.NS', 'MAHAPEXLTD.NS', 'AUSOMENT.NS', 'RHFL.NS', 'CAPTRUST.NS', 'KTKBANK.NS', 'WILLAMAGOR.NS', 'WELINV.NS', 'RPSGVENT.NS', 'ALMONDZ.NS', 'SATIN.NS', 'WEALTH.NS', 'KARURVYSYA.NS', 'LFIC.NS', 'HOTELRUGBY.NS', 'SCAPDVR.NS', 'SHAREINDIA.NS', 'EMKAY.NS', 'VIJIFIN.NS', 'J&KBANK.NS', 'DHFL.NS', 'CENTRUM.NS', 'KICL.NS', 'KHANDSE.NS', 'MASFIN.NS', 'MASKINVEST.NS', 'EBIXFOREX.NS', 'BFINVEST.NS', 'KEYFINSERV.NS', 'SILINV.NS', 'DHANBANK.NS', 'BSE.NS', 'ICRA.NS', 'PRIMESECU.NS', 'YAARII.NS', 'DVL.NS', 'HOMEFIRST.NS', 'VHL.NS', 'INVENTURE.NS', 'INFOMEDIA.NS', 'EQUITAS.NS', 'DHUNINV.NS']

    eng_sc = ['CONFIPET.NS', 'UNIDT.NS', 'MERCATOR.NS', 'LIKHITHA.NS', 'SELAN.NS', 'GMDCLTD.NS', 'REFEX.NS', 'CHENNPETRO.NS', 'DEEPINDS.NS', 'GULFPETRO.NS', 'SOUTHWEST.NS', 'DEEPENR.NS', 'ABAN.NS', 'ALPHAGEO.NS', 'AAKASH.NS', 'JINDRILL.NS', 'PANAMAPET.NS', 'HINDOILEXP.NS']

    cc_sc = ['LIBERTSHOE.NS', 'V2RETAIL.NS', 'MARALOVER.NS', 'LAOPALA.NS', 'LEMONTREE.NS', 'VAIBHAVGBL.NS', 'VARDHACRLC.NS', 'ATULAUTO.NS', 'MAHSCOOTER.NS', 'LYPSAGEMS.NS', 'LIBAS.NS', 'AUTOAXLES.NS', 'VARDMNPOLY.NS', 'LGBBROSLTD.NS', 'LUMAXIND.NS', 'LOVABLE.NS', 'AUTOIND.NS', 'LUMAXTECH.NS', 'MHRIL.NS', 'MAYURUNIQ.NS', 'NAHARSPING.NS', 'NAHARPOLY.NS', 'NAHARINDUS.NS', 'TVSSRICHAK.NS', 'NAGREEKEXP.NS', 'MUNJALSHOW.NS', 'MUNJALAU.NS', 'ASHIMASYN.NS', 'UCALFUEL.NS', 'UFLEX.NS', 'MAXVIL.NS', 'MORARJEE.NS', 'MOLDTKPAC.NS', 'MOHOTAIND.NS', 'MOHITIND.NS', 'ASIANHOTNR.NS', 'BURGERKING.NS', 'MIRZAINT.NS', 'MIRCELECTR.NS', 'MINDACORP.NS', 'LAMBODHARA.NS', 'MENONBE.NS', 'ACRYSIL.NS', 'MONTECARLO.NS', 'SPENTEX.NS', 'KKCL.NS', 'JAMNAAUTO.NS', 'WEIZMANIND.NS', 'BANG.NS', 'ITDC.NS', 'ISFT.NS', 'IRISDOREME.NS', 'BANSWRAS.NS', 'WHEELS.NS', 'BARBEQUE.NS', 'WONDERLA.NS', 'INDTERRAIN.NS', 'JAYBARMARU.NS', 'INDORAMA.NS', 'INDIANCARD.NS', 'WORTH.NS', 'BASML.NS', 'IMPAL.NS', 'ZENITHEXPO.NS', 'IGARASHI.NS', 'ZODIACLOTH.NS', 'ICIL.NS', 'HUHTAMAKI.NS', 'ZODJRDMKJ.NS', 'HSIL.NS', 'INDNIPPON.NS', 'BANCOINDIA.NS', 'JBFIND.NS', 'JBMA.NS', 'KITEX.NS', 'AYMSYNTEX.NS', 'KDDL.NS', 'VICEROY.NS', 'KANPRPLA.NS', 'VIDEOIND.NS', 'KANANIIND.NS', 'AARVEEDEN.NS', 'KAMATHOTEL.NS', 'VIPCLOTHNG.NS', 'VIPIND.NS', 'KALYANIFRG.NS', 'VISHAL.NS', 'JTEKTINDIA.NS', 'VIVIDHA.NS', 'BALKRISHNA.NS', 'JMTAUTOLTD.NS', 'JMA.NS', 'JKTYRE.NS', 'JINDWORLD.NS', 'BANARBEADS.NS', 'JIKIND.NS', 'KHADIM.NS', 'TTL.NS', 'SETCO.NS', 'SARLAPOLY.NS', 'SANGAMIND.NS', 'SANDHAR.NS', 'ALPSINDUS.NS', 'SALONA.NS', 'AMBIKCO.NS', 'SUPERHOUSE.NS', 'SAFARI.NS', 'SUPERSPIN.NS', 'SUNDRMBRAK.NS', 'RUSHIL.NS', 'AMDIND.NS', 'RUBYMILLS.NS', 'RSWM.NS', 'SUPRAJIT.NS', 'ROHLTD.NS', 'RML.NS', 'RMCL.NS', 'RICOAUTO.NS', 'RGL.NS', 'REMSONSIND.NS', 'SURYALAXMI.NS', 'RUPA.NS', 'RBL.NS', 'SHANKARA.NS', 'SPENCERS.NS', 'SPTL.NS', 'SPECIALITY.NS', 'SPAL.NS', 'SOMATEX.NS', 'SMLISUZU.NS', 'SIYSIL.NS', 'SPYL.NS', 'SREEL.NS', 'SINTEX.NS', 'AHLWEST.NS', 'SINTERCOM.NS', 'SSWL.NS', 'SGL.NS', 'SILGO.NS', 'AHLEAST.NS', 'SHRIPISTON.NS', 'STOVEKRAFT.NS', 'SHREERAMA.NS', 'SHOPERSTOP.NS', 'SHIVATEX.NS', 'SHIVAMILLS.NS', 'SHIVAMAUTO.NS', 'SHIL.NS', 'SUBROS.NS', 'SHARDAMOTR.NS', 'SUMEETINDS.NS', 'SIL.NS', 'ASAL.NS', 'RAYMOND.NS', 'RANEHOLDIN.NS', 'PCJEWELLER.NS', 'PATSPINLTD.NS', 'THOMASCOTT.NS', 'TIMETECHNO.NS', 'ORIENTLTD.NS', 'ORIENTHOT.NS', 'ORICONENT.NS', 'ORBTEXP.NS', 'OMAXAUTO.NS', 'OLECTRA.NS', 'ARCHIES.NS', 'TMRVL.NS', 'NRBBEARING.NS', 'TOKYOPLAST.NS', 'NITINSPIN.NS', 'NILKAMAL.NS', 'ARVIND.NS', 'ARVINDFASN.NS', 'NDRAUTO.NS', 'NDL.NS', 'SPLIL.NS', 'ARROWGREEN.NS', 'ADVANIHOTR.NS', 'PEARLPOLY.NS', 'PGIL.NS', 'RANEENGINE.NS', 'SUTLEJTEX.NS', 'SUULD.NS', 'SWANENERGY.NS', 'SWARAJENG.NS', 'RAJRAYON.NS', 'TAJGVK.NS', 'TALBROAUTO.NS', 'ADL.NS', 'THOMASCOOK.NS', 'PRICOLLTD.NS', 'TCNSBRANDS.NS', 'PRECOT.NS', 'PRECAM.NS', 'TCPLPACK.NS', 'PRAXIS.NS', 'PRADIP.NS', 'PPAP.NS', 'TGBHOTELS.NS', 'PIONEEREMB.NS', 'PILITA.NS', 'APOLSINHOT.NS', 'THANGAMAYL.NS', 'TBZ.NS', 'BUTTERFLY.NS', 'MITTAL.NS', 'HLVLTD.NS', 'GANECOS.NS', 'DPABHUSHAN.NS', 'DONEAR.NS', 'DOLLAR.NS', 'HAVISHA.NS', 'GBGLOBAL.NS', 'BHARATGEAR.NS', 'GINNIFILA.NS', 'DYNAMATECH.NS', 'DELTACORP.NS', 'BOROLTD.NS', 'BORORENEW.NS', 'DCMNVL.NS', 'GNA.NS', 'FELDVR.NS', 'DAMODARIND.NS', 'BHANDARI.NS', 'GLOBE.NS', 'EASEMYTRIP.NS', 'EASTSILK.NS', 'BIL.NS', 'FIEMIND.NS', 'FILATEX.NS', 'BIRLATYRE.NS', 'EUROTEXIND.NS', 'BKMINDST.NS', 'FLEXITUFF.NS', 'FLFL.NS', 'EMMBI.NS', 'ELGIRUBCO.NS', 'FMGOETZE.NS', 'FORCEMOT.NS', 'FRETAIL.NS', 'EIHAHOTELS.NS', 'GRPLTD.NS', 'GABRIEL.NS', 'HIMATSEIDE.NS', 'DANGEE.NS', 'HINDCOMPOS.NS', 'GOKEX.NS', 'CHALET.NS', 'CRAFTSMAN.NS', 'GOLDIAM.NS', 'GOODYEAR.NS', 'GREENLAM.NS', 'GREENPANEL.NS', 'BRFL.NS', 'CENTENKA.NS', 'CCHHL.NS', 'CASTEXTECH.NS', 'HITECHCORP.NS', 'HITECHGEAR.NS', 'CANTABIL.NS', 'BSL.NS', 'BYKE.NS', 'CELEBRITY.NS', 'COFFEEDAY.NS', 'GTNTEX.NS', 'FEL.NS', 'GOENKA.NS', 'COX&KINGS.NS', 'CORALFINAC.NS', 'HINDNATGLS.NS', 'COSMOFILMS.NS', 'HINDMOTORS.NS']

    cs_sc = ['JAINSTUDIO.NS', 'JAGRAN.NS', 'RCOM.NS', 'INOXLEISUR.NS', 'SABEVENTS.NS', 'SABTN.NS', 'SAMBHAAV.NS', 'SANDESH.NS', 'SAREGAMA.NS', 'MATRIMONY.NS', 'DNAMEDIA.NS', 'SHEMAROO.NS', 'DISHTV.NS', 'IMAGICAA.NS', 'HTMEDIA.NS', 'SILLYMONKS.NS', 'DGCONTENT.NS', 'SITINET.NS', 'ENIL.NS', 'SCHAND.NS', 'RAJTV.NS', 'EROSMEDIA.NS', 'NAVNETEDUL.NS', 'NDTV.NS', 'NETWORK18.NS', 'NEXTMEDIA.NS', 'DEN.NS', 'NXTDIGITAL.NS', 'ONMOBILE.NS', 'GFLLIMITED.NS', 'GTL.NS', 'ORTEL.NS', 'GTPL.NS', 'PFOCUS.NS', 'PNC.NS', 'MUKTAARTS.NS', 'JUSTDIAL.NS', 'PRESSMN.NS', 'MTNL.NS', 'BALAJITELE.NS', 'HATHWAY.NS', 'MPSLTD.NS', 'BCG.NS', 'RADAAN.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'BAGFILMS.NS', 'HMVL.NS', 'DALALSTCOM.NS', 'UFO.NS', 'CYBERMEDIA.NS', 'TIPSINDLTD.NS', 'DBCORP.NS', 'TVVISION.NS', 'TOUCHWOOD.NS', 'TVTODAY.NS', 'ZEEMEDIA.NS', 'CINEVISTA.NS', 'VERTOZ.NS', 'CREATIVEYE.NS', 'TTML.NS']
 
    bm_sc = ['VALIANTORG.NS', 'JKLAKSHMI.NS', 'GSFC.NS', 'SUDARSCHEM.NS', 'RCF.NS', 'JSL.NS', 'TATASTLLP.NS', 'RESPONIND.NS', 'MOIL.NS', 'DHANUKA.NS', 'STARCEMENT.NS', 'PRIVISCL.NS', 'JSLHISAR.NS', 'MIDHANI.NS', 'WELCORP.NS', 'GULFOILLUB.NS', 'PHILIPCARB.NS', 'MEGH.NS', 'JINDALPOLY.NS', 'POLYPLEX.NS', 'NFL.NS', 'GPIL.NS', 'NOCIL.NS', 'TATAMETALI.NS', 'GUJALKALI.NS', 'SHARDACROP.NS', 'HERANBA.NS', 'JSWISPL.NS', 'DEEPAKFERT.NS', 'JINDALSAW.NS', 'OAL.NS', 'BEPL.NS', 'ASTEC.NS', 'JKPAPER.NS', 'GREENPLY.NS', 'ORIENTCEM.NS', 'GHCL.NS', 'SURYAROSNI.NS', 'MAITHANALL.NS', 'INEOSSTYRO.NS', 'CAMLINFINE.NS', 'TINPLATE.NS', 'HSCL.NS', 'NEOGEN.NS', 'MAHSEAMLES.NS', 'SARDAEN.NS', 'SAGCEM.NS', 'TIDEWATER.NS', 'JAICORPLTD.NS', 'MUKANDLTD.NS', 'CHEMCON.NS', 'APCOTEXIND.NS', 'PRAKASH.NS', 'KIRIINDUS.NS', 'USHAMART.NS', 'KSL.NS', 'ORISSAMINE.NS', 'INDIAGLYCO.NS', 'GALLISPAT.NS', 'SOTL.NS', 'SUNFLAG.NS', 'IGPL.NS', 'PUNJABCHEM.NS', 'KCP.NS', 'MANALIPETC.NS', 'ELECTCAST.NS', 'EXCELINDUS.NS', 'ASHAPURMIN.NS', 'WSTCSTPAPR.NS', 'IFGLEXPOR.NS', 'KESORAMIND.NS', 'ESTER.NS', 'JAYNECOIND.NS', 'BODALCHEM.NS', 'SANGHIIND.NS', 'IMFA.NS', 'MANGCHEFER.NS', 'ANDHRSUGAR.NS', 'AARTISURF.NS', 'INSECTICID.NS', 'CLNINDIA.NS', 'FAIRCHEMOR.NS', 'KINGFA.NS', 'TIRUMALCHM.NS', 'SHREDIGCEM.NS', 'RAJRATAN.NS', 'NACLIND.NS', 'VIDHIING.NS', 'GOCLCORP.NS', 'SESHAPAPER.NS', 'TNPL.NS', 'OCCL.NS', 'SIRCA.NS', 'ANDHRAPAP.NS', 'FCL.NS', 'BHAGERIA.NS', 'FOSECOIND.NS', 'DCW.NS', 'NCLIND.NS', 'SPIC.NS', 'SATIA.NS', 'NATHBIOGEN.NS', 'AVTNPL.NS', 'TNPETRO.NS', 'VSSL.NS', 'MANGLMCEM.NS', 'SALASAR.NS', 'GULPOLY.NS', 'UNIENTER.NS', 'PLASTIBLEN.NS', 'DECCANCE.NS', 'BESTAGRO.NS', 'KUANTUM.NS', 'APCL.NS', 'DYNPRO.NS', 'KANORICHEM.NS', 'MANINDS.NS', 'JAIBALAJI.NS', 'ORIENTPPR.NS', 'JAYAGROGN.NS', 'SHREEPUSHK.NS', 'GALLANTT.NS', 'STEELXIND.NS', 'SHALPAINTS.NS', 'NAGAFERT.NS', 'SRHHYPOLTD.NS', 'JUBLINDS.NS', 'MADRASFERT.NS', 'ASAHISONG.NS', 'MSPL.NS', 'ZUARI.NS', 'KAMDHENU.NS', 'NRAIL.NS', 'HITECH.NS', 'VISHNU.NS', 'BHARATWIRE.NS', 'DICIND.NS', 'GSCLCEMENT.NS', 'CHEMBOND.NS', 'ORIENTABRA.NS', 'GOACARBON.NS', 'VINYLINDIA.NS', 'ISMTLTD.NS', 'MCL.NS', 'PODDARMENT.NS', 'RAMANEWS.NS', 'AKSHARCHEM.NS', 'MMP.NS', 'KOTHARIPET.NS', 'AGARIND.NS', 'PDMJEPAPER.NS', 'ARVEE.NS', 'KRISHANA.NS', 'CHEMFAB.NS', 'GENUSPAPER.NS', 'STARPAPER.NS', 'SHYAMCENT.NS', 'ASTRON.NS', 'KAKATCEM.NS', 'MBAPL.NS', 'ANDHRACEMT.NS', 'MANAKSTEEL.NS', 'BALLARPUR.NS', 'BHAGYANGR.NS', '20MICRONS.NS', 'PREMEXPLN.NS', 'BSHSL.NS', 'RUCHIRA.NS', 'JOCIL.NS', 'ARIES.NS', 'SEYAIND.NS', 'ADHUNIKIND.NS', 'MAHASTEEL.NS', 'MAANALU.NS', 'XPROINDIA.NS', 'RAMASTEEL.NS', 'SHREYANIND.NS', 'VISASTEEL.NS', 'UTTAMSTL.NS', 'IVP.NS', 'SHRENIK.NS', 'VIKASWSP.NS', 'RAJMET.NS', 'VIKASPROP.NS', 'SIGIND.NS', 'MANAKALUCO.NS', 'PREMIERPOL.NS', 'SICAGEN.NS', 'BEDMUTHA.NS', 'ABMINTLTD.NS', 'SAGARDEEP.NS', 'VIKASECO.NS', 'ARCHIDPLY.NS', 'SUPREMEENG.NS', 'TAINWALCHM.NS', 'HISARMETAL.NS', 'ALKALI.NS', 'SUNDARAM.NS', 'CENTEXT.NS', 'WIPL.NS', 'GAL.NS', 'MALUPAPER.NS', 'CUBEXTUB.NS', 'BVCL.NS', 'VASWANI.NS', 'SALSTEEL.NS', 'SANGINITA.NS', 'KRIDHANINF.NS', 'ROHITFERRO.NS', 'AGROPHOS.NS', 'NATNLSTEEL.NS', 'BURNPUR.NS', 'PRAKASHSTL.NS', 'SEPOWER.NS', 'MANGTIMBER.NS', 'ANKITMETAL.NS', 'MAGNUM.NS', 'ZENITHSTL.NS', 'JIYAECO.NS', 'IMPEXFERRO.NS', 'SMPL.NS', 'GFSTEELS.NS', 'NTL.NS', 'ARENTERP.NS']    

    util = ['BAJAJELEC.NS', 'MGL.NS', 'JSWENERGY.NS', 'RTNINDIA.NS', 'RPOWER.NS', 'RTNPOWER.NS', 'TORNTPOWER.NS', 'IGL.NS', 'CESC.NS', 'ATGL.NS', 'DPSCLTD.NS', 'GAIL.NS', 'RELINFRA.NS', 'ADANIPOWER.NS', 'GIPCL.NS', 'INDOWIND.NS', 'TATAPOWER.NS', 'NHPC.NS', 'KARMAENG.NS', 'SJVN.NS', 'PTC.NS', 'NLCINDIA.NS', 'ADANIGREEN.NS', 'GREENPOWER.NS', 'NBVENTURES.NS', 'GUJGASLTD.NS', 'ADANITRANS.NS', 'GSPL.NS', 'ENERGYDEV.NS', 'POWERGRID.NS', 'JPPOWER.NS', 'NTPC.NS', 'SURANAT&P.NS'] 

    tech = ['LTTS.NS', 'MIC.NS', 'VAKRANGEE.NS', 'UJAAS.NS', 'CENTUM.NS', 'MINDTECK.NS', 'XCHANGING.NS', 'KELLTONTEC.NS', '3IINFOTECH.NS', 'MASTEK.NS', 'WIPRO.NS', 'KPITTECH.NS', 'LTI.NS', 'XELPMOC.NS', 'WHIRLPOOL.NS', 'AURIONPRO.NS', 'GTLINFRA.NS', 'ACCELYA.NS', 'MAJESCO.NS', 'GSS.NS', 'WEBELSOLAR.NS', 'ASTRAMICRO.NS', 'CEREBRAINT.NS', 'JUMPNET.NS', 'GOLDTECH.NS', 'MEGASOFT.NS', 'MINDTREE.NS', 'MELSTAR.NS', 'ZENSARTECH.NS', 'URJA.NS', 'BSOFT.NS', 'CALSOFT.NS', 'HOVS.NS', 'AMBER.NS', 'IFBIND.NS', 'EXPLEOSOL.NS', 'BIRLACABLE.NS', 'FCSSOFT.NS', 'SONATSOFTW.NS', 'POWERINDIA.NS', 'AIRAN.NS', 'JCHAC.NS', 'PGEL.NS', 'PERSISTENT.NS', 'HCLTECH.NS', 'SMARTLINK.NS', 'PARACABLES.NS', 'PALREDTEC.NS', 'HCL-INSYS.NS', 'STLTECH.NS', 'SUBEXLTD.NS', 'DATAMATICS.NS', 'HAPPSTMNDS.NS', 'AGCNET.NS', 'BARTRONICS.NS', 'CYBERTECH.NS', 'FSL.NS', 'PANACHE.NS', 'QUICKHEAL.NS', 'INFIBEAM.NS', 'INFOBEAN.NS', 'ECLERX.NS', 'INTENTECH.NS', 'INTELLECT.NS', 'DSSL.NS', 'RSYSTEMS.NS', 'RSSOFTWARE.NS', 'SASKEN.NS', 'ROLTA.NS', 'DRCSYSTEMS.NS', 'INSPIRISYS.NS', 'SECURKLOUD.NS', 'ITI.NS', 'HFCL.NS', 'REDINGTON.NS', 'IZMO.NS', 'DLINKINDIA.NS', 'DIXON.NS', 'DIGISPICE.NS', 'INFY.NS', 'RAMCOSYS.NS', 'ALANKIT.NS', 'AKSHOPTFBR.NS', 'SHYAMTEL.NS', 'OPTIEMUS.NS', 'ONWARDTEC.NS', 'INDOSOLAR.NS', 'TEJASNET.NS', 'BPL.NS', 'NEWGEN.NS', 'TCS.NS', 'TECHM.NS', 'SURANASOL.NS', 'NELCO.NS', 'TERASOFT.NS', 'COMPINFO.NS', 'GENESYS.NS', 'COFORGE.NS', 'TNTELE.NS', 'MRO-TEK.NS', 'TREJHARA.NS', 'TRIGYN.NS', 'MPHASIS.NS', 'CIGNITITEC.NS', 'TVSELECT.NS', 'SAKSOFT.NS', 'TATAELXSI.NS', 'KERNEX.NS', 'NITIRAJ.NS', 'SWELECTES.NS', 'SWSOLAR.NS', 'NUCLEUS.NS', 'CREATIVE.NS', 'SUVIDHAA.NS', 'TANLA.NS', 'OFSS.NS', 'ADSL.NS', 'ADROITINFO.NS', 'CTE.NS']

    re = ['KOLTEPATIL.NS', 'TECHIN.NS', 'BRIGADE.NS', 'EMAMIREAL.NS', 'TCIDEVELOP.NS', 'CINELINE.NS', 'MODIRUBBER.NS', 'TEXINFRA.NS', 'RVHL.NS', 'MOTOGENFIN.NS', 'ARVSMART.NS', 'GEECEE.NS', 'BHAGYAPROP.NS', 'UNITECH.NS', 'ASHIANA.NS', 'AMJLAND.NS', 'ANANTRAJ.NS', 'COUNCODOS.NS', 'DBREALTY.NS', 'NILASPACES.NS', 'ARIHANTSUP.NS', 'SUNTECK.NS', 'PTL.NS', 'ARIHANT.NS', 'NILAINFRA.NS', 'FMNL.NS', 'SUMIT.NS', 'OSWALAGRO.NS', 'VIPULLTD.NS', 'HUBTOWN.NS', 'PRESTIGE.NS', 'KARDA.NS', 'HDIL.NS', 'PARSVNATH.NS', 'PENINLAND.NS', 'SOBHA.NS', 'PHOENIXLTD.NS', 'AJMERA.NS', 'PRAENG.NS', 'LPDC.NS', 'BOMDYEING.NS', 'PODDARHOUS.NS', 'LODHA.NS', 'MAHLIFE.NS', 'OMAXE.NS', 'PROZONINTU.NS', 'IBREALEST.NS', 'GODREJPROP.NS', 'TARC.NS', 'BSELINFRA.NS', 'SHRADHA.NS', 'ANSALAPI.NS', 'ANSALHSG.NS', 'HEMIPROP.NS', 'MARATHON.NS', 'GANESHHOUC.NS', 'OBEROIRLTY.NS', 'DLF.NS']

    ind = ['3MINDIA.NS', 'ABB.NS', 'HONAUT.NS', 'VOLTAS.NS', 'CONCOR.NS', 'INDIGO.NS', 'CUMMINSIND.NS', 'SIEMENS.NS', 'ADANIPORTS.NS', 'ASTRAL.NS', 'BHEL.NS', 'LT.NS', 'HAL.NS', 'HAVELLS.NS', 'POLYCAB.NS', 'BEL.NS', 'IRCTC.NS']

    health = ['FORTIS.NS', 'PANACEABIO.NS', 'ALPA.NS', 'ORTINLAB.NS', 'IOLCP.NS', 'HESTERBIO.NS', 'ORCHPHARMA.NS', 'BALPHARMA.NS', 'INDOCO.NS', 'SUNPHARMA.NS', 'OPTOCIRCUI.NS', 'HIKAL.NS', 'DRREDDY.NS', 'INDSWFTLTD.NS', 'INDSWFTLAB.NS', 'SMSLIFE.NS', 'ERIS.NS', 'SMSPHARMA.NS', 'APLLTD.NS', 'SOLARA.NS', 'JAGSNPHARM.NS', 'AJANTPHARM.NS', 'JBCHEPHARM.NS', 'APOLLOHOSP.NS', 'ALBERTDAVD.NS', 'ALEMBICLTD.NS', 'DIVISLAB.NS', 'SPARC.NS', 'INDRAMEDCO.NS', 'SHILPAMED.NS', 'STAR.NS', 'BIOCON.NS', 'SASTASUNDR.NS', 'DCAL.NS', 'RPGLIFE.NS', 'PFIZER.NS', 'SANOFI.NS', 'BIOFILCHEM.NS', 'BLISSGVS.NS', 'SEQUENT.NS', 'PGHL.NS', 'SHALBY.NS', 'ALKEM.NS', 'FDC.NS', 'AMRUTANJAN.NS', 'POLYMED.NS', 'IPCALAB.NS', 'SUVEN.NS', 'GLENMARK.NS', 'GLAXO.NS', 'MOREPENLAB.NS', 'GLAND.NS', 'VIVIMEDLAB.NS', 'CIPLA.NS', 'TORNTPHARM.NS', 'GRANULES.NS', 'MARKSANS.NS', 'AARTIDRUGS.NS', 'NATCOPHARM.NS', 'THYROCARE.NS', 'THEMISMED.NS', 'LINCOLN.NS', 'NECLIFE.NS', 'LUPIN.NS', 'CAPLIPOINT.NS', 'TTKHLTCARE.NS', 'BROOKS.NS', 'ASTERDM.NS', 'MAXHEALTH.NS', 'MAXIND.NS', 'VENUSREM.NS', 'ASTRAZEN.NS', 'MANGALAM.NS', 'ABBOTINDIA.NS', 'GUFICBIO.NS', 'UNIVPHOTO.NS', 'VIMTALABS.NS', 'UNICHEMLAB.NS', 'METROPOLIS.NS', 'JUBLPHARMA.NS', 'JUBLINGREA.NS', 'AUROPHARMA.NS', 'LYKALABS.NS', 'WANBURY.NS', 'LOTUSEYE.NS', 'VAISHALI.NS', 'KREBSBIO.NS', 'KILITCH.NS', 'TAKE.NS', 'SAKAR.NS', 'NOVARTIND.NS', 'WOCKPHARMA.NS', 'KOPRAN.NS', 'SYNCOM.NS', 'ZOTA.NS', 'HCG.NS', 'LALPATHLAB.NS', 'BAFNAPH.NS', 'NH.NS', 'LAURUSLABS.NS', 'NEULANDLAB.NS', 'SUVENPHAR.NS', 'CADILAHC.NS', 'LASA.NS', 'NURECA.NS', 'SYNGENE.NS']
 
    fs = ['CHOLAHLDNG.NS', 'IFCI.NS', 'ARMANFIN.NS', 'GLFL.NS', 'SOUTHBANK.NS', 'TCIFINANCE.NS', 'BAJFINANCE.NS', 'CREDITACC.NS', 'SPANDANA.NS', 'SUNDARMFIN.NS', 'PNBHOUSING.NS', 'PNBGILTS.NS', 'NSIL.NS', 'BINDALAGRO.NS', 'MOTILALOFS.NS', 'CREST.NS', 'CRISIL.NS', 'PNB.NS', 'IDBI.NS', 'MCX.NS', 'CUB.NS', 'SMCGLOBAL.NS', 'ONELIFECAP.NS', 'HDFCLIFE.NS', 'IDFC.NS', 'MFSL.NS', 'CHOLAFIN.NS', 'UJJIVANSFB.NS', 'UJJIVAN.NS', 'CSBBANK.NS', 'IDFCFIRSTB.NS', 'UCOBANK.NS', 'IEX.NS', 'SURYODAY.NS', 'INDIANB.NS', 'BAJAJHLDNG.NS', 'BIRLAMONEY.NS', 'SUMMITSEC.NS', 'GICRE.NS', 'INDOSTAR.NS', 'TATAINVEST.NS', 'NBIFIN.NS', 'SREINFRA.NS', 'THEINVEST.NS', 'IITL.NS', 'STEELCITY.NS', 'NDGL.NS', 'PFS.NS', 'TFL.NS', 'TFCILTD.NS', 'PFC.NS', 'DCBBANK.NS', 'PEL.NS', 'SRTRANSFIN.NS', 'DBSTOCKBRO.NS', 'CONSOFINVT.NS', 'JMFINANCIL.NS', 'IIFLWAM.NS', 'IIFLSEC.NS', 'IIFL.NS', 'JINDALPHOT.NS', 'NIACL.NS', 'FEDERALBNK.NS', 'MUTHOOTCAP.NS', 'MUTHOOTFIN.NS', 'HDFCBANK.NS', 'GICHSGFIN.NS', 'INDBANK.NS', 'NAGREEKCAP.NS', 'PAISALO.NS', 'HDFCAMC.NS', 'INDOTHAI.NS', 'PILANIINVS.NS', 'TIMESGTY.NS', 'NAM-INDIA.NS', 'HBSL.NS', 'HDFC.NS', 'GEOJITFSL.NS', 'BANDHANBNK.NS', 'NAHARCAP.NS', 'DCMFINSERV.NS', 'UNIONBANK.NS', 'VLSFINANCE.NS', 'REPCOHOME.NS', 'IVC.NS', 'MCDHOLDING.NS', '5PAISA.NS', 'RELIGARE.NS', 'RELCAPITAL.NS', 'CARERATING.NS', 'BANKBARODA.NS', 'RECLTD.NS', 'HEXATRADEX.NS', 'M&MFIN.NS', 'HUDCO.NS', 'CDSL.NS', 'BLBLIMITED.NS', 'DOLAT.NS', 'MAGMA.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'MAHAPEXLTD.NS', 'AUBANK.NS', 'AUSOMENT.NS', 'RHFL.NS', 'IRFC.NS', 'CAPTRUST.NS', 'KTKBANK.NS', 'L&TFH.NS', 'WILLAMAGOR.NS', 'WELINV.NS', 'RPSGVENT.NS', 'BANKINDIA.NS', 'ALMONDZ.NS', 'ISEC.NS', 'CANBK.NS', 'SATIN.NS', 'WEALTH.NS', 'KARURVYSYA.NS', 'LFIC.NS', 'HOTELRUGBY.NS', 'CAMS.NS', 'KOTAKBANK.NS', 'SBICARD.NS', 'SBILIFE.NS', 'SBIN.NS', 'LICHSGFIN.NS', 'SCAPDVR.NS', 'AAVAS.NS', 'SHAREINDIA.NS', 'EMKAY.NS', 'VIJIFIN.NS', 'J&KBANK.NS', 'DHFL.NS', 'CENTRALBK.NS', 'CENTRUM.NS', 'KICL.NS', 'KHANDSE.NS', 'SHRIRAMCIT.NS', 'MASFIN.NS', 'MASKINVEST.NS', 'ICICIPRULI.NS', 'EBIXFOREX.NS', 'BFINVEST.NS', 'KEYFINSERV.NS', 'DHANI.NS', 'SILINV.NS', 'DHANBANK.NS', 'BSE.NS', 'ICRA.NS', 'INDUSINDBK.NS', 'UTIAMC.NS', 'PSB.NS', 'PRIMESECU.NS', 'BAJAJFINSV.NS', 'IOB.NS', 'ICICIGI.NS', 'ICICIBANK.NS', 'YAARII.NS', 'YESBANK.NS', 'DVL.NS', 'HOMEFIRST.NS', 'VHL.NS', 'EDELWEISS.NS', 'ANGELBRKG.NS', 'INVENTURE.NS', 'IBULHSGFIN.NS', 'CANFINHOME.NS', 'AXISBANK.NS', 'INFOMEDIA.NS', 'EQUITAS.NS', 'DHUNINV.NS', 'EQUITASBNK.NS', 'MANAPPURAM.NS', 'ABCAPITAL.NS']

    eng = ['ADANIENT.NS', 'CONFIPET.NS', 'ONGC.NS', 'UNIDT.NS', 'MERCATOR.NS', 'PETRONET.NS', 'LIKHITHA.NS', 'SELAN.NS', 'GMDCLTD.NS', 'RELIANCE.NS', 'REFEX.NS', 'COALINDIA.NS', 'CHENNPETRO.NS', 'DEEPINDS.NS', 'GULFPETRO.NS', 'SOUTHWEST.NS', 'DEEPENR.NS', 'MRPL.NS', 'ABAN.NS', 'BPCL.NS', 'OIL.NS', 'ALPHAGEO.NS', 'AAKASH.NS', 'HINDPETRO.NS', 'JINDRILL.NS', 'AEGISCHEM.NS', 'PANAMAPET.NS', 'IOC.NS', 'HINDOILEXP.NS']

    cd = ['GODFRYPHLP.NS', 'AVANTIFEED.NS', 'MCDOWELL-N.NS', 'PALASHSECU.NS', 'ASPINWALL.NS', 'PARAGMILK.NS', 'KSCL.NS', 'PGHH.NS', 'GROBTEA.NS', 'KOTARISUG.NS', 'MGEL.NS', 'MCLEODRUSS.NS', 'KMSUGAR.NS', 'APTECHT.NS', 'KRBL.NS', 'AVADHSUGAR.NS', 'ASALCBR.NS', 'GMBREW.NS', 'NESTLEIND.NS', 'ATFL.NS', 'MTEDUCARE.NS', 'GOKUL.NS', 'GOKULAGRO.NS', 'GOLDENTOBC.NS', 'GANGESSECU.NS', 'NIITLTD.NS', 'GILLETTE.NS', 'GLOBAL.NS', 'MAGADSUGAR.NS', 'NKIND.NS', 'NORBTEAEXP.NS', 'GODREJCP.NS', 'MAWANASUG.NS', 'GODREJAGRO.NS', 'GAEL.NS', 'GLOBUSSPR.NS', 'MARICO.NS', 'LCCINFOTEC.NS', 'RUCHI.NS', 'PKTEA.NS', 'DABUR.NS', 'DAAWAT.NS', 'CUPID.NS', 'TASTYBITE.NS', 'TATACOFFEE.NS', 'TATACONSUM.NS', 'ADFFOODS.NS', 'COMPUSOFT.NS', 'THIRUSUGAR.NS', 'COLPAL.NS', 'TI.NS', 'CLEDUCATE.NS', 'TREEHOUSE.NS', 'TRIVENI.NS', 'DALMIASUG.NS', 'BRITANNIA.NS', 'UGARSUGAR.NS', 'UMANGDAIRY.NS', 'UMESLTD.NS', 'UNITEDTEA.NS', 'UTTAMSUGAR.NS', 'VADILALIND.NS', 'VBL.NS', 'VENKEYS.NS', 'CCL.NS', 'VISHWARAJ.NS', 'CAREERP.NS', 'VSTIND.NS', 'WATERBASE.NS', 'ZEELEARN.NS', 'UBL.NS', 'PIONDIST.NS', 'AGRITECH.NS', 'SRPL.NS', 'PONNIERODE.NS', 'FCONSUMER.NS', 'APEX.NS', 'RADICO.NS', 'RAJSREESUG.NS', 'ANIKINDS.NS', 'RANASUG.NS', 'EMAMILTD.NS', 'RENUKA.NS', 'RKDL.NS', 'ROSSELLIND.NS', 'RUCHINFRA.NS', 'EIDPARRY.NS', 'EDUCOMP.NS', 'STEL.NS', 'SAKHTISUG.NS', 'DWARKESH.NS', 'DTIL.NS', 'SANWARIA.NS', 'SDBL.NS', 'DMART.NS', 'SHK.NS', 'DIAMONDYD.NS', 'DHARSUGAR.NS', 'AKG.NS', 'SIMBHALS.NS', 'DHAMPURSUG.NS', 'DFMFOODS.NS', 'SKMEGGPROD.NS', 'AJOONI.NS', 'SAKUMA.NS', 'KGL.NS', 'ZYDUSWELL.NS', 'JYOTHYLAB.NS', 'ITC.NS', 'KCPSUGIND.NS', 'HERITGFOOD.NS', 'HINDUNILVR.NS', 'BANARISUG.NS', 'JHS.NS', 'BCLIND.NS', 'HATSUN.NS', 'HARRMALAYA.NS', 'BAJAJCON.NS', 'KAYA.NS', 'KEERTI.NS', 'BECTORFOOD.NS', 'BALRAMCHIN.NS', 'HNDFDS.NS', 'JAYSREETEA.NS', 'BAJAJHIND.NS', 'IFBAGRO.NS']

    cc = ['LIBERTSHOE.NS', 'V2RETAIL.NS', 'MARUTI.NS', 'MARALOVER.NS', 'LAOPALA.NS', 'LEMONTREE.NS', 'VAIBHAVGBL.NS', 'VARDHACRLC.NS', 'ATULAUTO.NS', 'MAHSCOOTER.NS', 'LYPSAGEMS.NS', 'M&M.NS', 'LIBAS.NS', 'AUTOAXLES.NS', 'LUXIND.NS', 'VARDMNPOLY.NS', 'LGBBROSLTD.NS', 'LUMAXIND.NS', 'LOVABLE.NS', 'AUTOIND.NS', 'VARROC.NS', 'MAHINDCIE.NS', 'LUMAXTECH.NS', 'MHRIL.NS', 'MAYURUNIQ.NS', 'NAHARSPING.NS', 'NAHARPOLY.NS', 'NAHARINDUS.NS', 'TVSMOTOR.NS', 'TVSSRICHAK.NS', 'NAGREEKEXP.NS', 'MUNJALSHOW.NS', 'MUNJALAU.NS', 'ASHIMASYN.NS', 'UCALFUEL.NS', 'MRF.NS', 'UFLEX.NS', 'MOTHERSUMI.NS', 'MAXVIL.NS', 'MORARJEE.NS', 'MOLDTKPAC.NS', 'ASHOKLEY.NS', 'MOHOTAIND.NS', 'MOHITIND.NS', 'ASIANHOTNR.NS', 'BURGERKING.NS', 'MIRZAINT.NS', 'MIRCELECTR.NS', 'MINDAIND.NS', 'MINDACORP.NS', 'LAMBODHARA.NS', 'MENONBE.NS', 'ACRYSIL.NS', 'MONTECARLO.NS', 'ABFRL.NS', 'SPENTEX.NS', 'KKCL.NS', 'JAMNAAUTO.NS', 'WEIZMANIND.NS', 'BANG.NS', 'WELSPUNIND.NS', 'WESTLIFE.NS', 'ITDC.NS', 'ISFT.NS', 'IRISDOREME.NS', 'BANSWRAS.NS', 'WHEELS.NS', 'BARBEQUE.NS', 'WONDERLA.NS', 'INDTERRAIN.NS', 'JAYBARMARU.NS', 'INDORAMA.NS', 'INDIANCARD.NS', 'WORTH.NS', 'BASML.NS', 'INDHOTEL.NS', 'BATAINDIA.NS', 'IMPAL.NS', 'ZENITHEXPO.NS', 'IGARASHI.NS', 'ZODIACLOTH.NS', 'ICIL.NS', 'HUHTAMAKI.NS', 'ZODJRDMKJ.NS', 'HSIL.NS', 'INDNIPPON.NS', 'BANCOINDIA.NS', 'JBFIND.NS', 'JBMA.NS', 'KITEX.NS', 'AYMSYNTEX.NS', 'KDDL.NS', 'VICEROY.NS', 'BAJAJ-AUTO.NS', 'KANPRPLA.NS', 'VIDEOIND.NS', 'KANANIIND.NS', 'AARVEEDEN.NS', 'KAMATHOTEL.NS', 'KALYANKJIL.NS', 'VIPCLOTHNG.NS', 'VIPIND.NS', 'KALYANIFRG.NS', 'VISHAL.NS', 'JUBLFOOD.NS', 'JTEKTINDIA.NS', 'VIVIDHA.NS', 'VMART.NS', 'VTL.NS', 'BALKRISHNA.NS', 'JMTAUTOLTD.NS', 'JMA.NS', 'JKTYRE.NS', 'BALKRISIND.NS', 'WABCOINDIA.NS', 'JINDWORLD.NS', 'BANARBEADS.NS', 'JIKIND.NS', 'KPRMILL.NS', 'KHADIM.NS', 'TRIDENT.NS', 'TTL.NS', 'SETCO.NS', 'SARLAPOLY.NS', 'SUNDRMFAST.NS', 'ALOKINDS.NS', 'SANGAMIND.NS', 'SANDHAR.NS', 'ALPSINDUS.NS', 'SALONA.NS', 'AMARAJABAT.NS', 'AMBIKCO.NS', 'SUPERHOUSE.NS', 'SAFARI.NS', 'SUPERSPIN.NS', 'SUNDRMBRAK.NS', 'RUSHIL.NS', 'AMDIND.NS', 'RUBYMILLS.NS', 'RSWM.NS', 'SUPRAJIT.NS', 'ROHLTD.NS', 'RML.NS', 'RMCL.NS', 'RICOAUTO.NS', 'RGL.NS', 'REMSONSIND.NS', 'RELAXO.NS', 'SUPREMEIND.NS', 'SURYALAXMI.NS', 'RUPA.NS', 'RBL.NS', 'SFL.NS', 'SHANKARA.NS', 'SPENCERS.NS', 'SPTL.NS', 'SPECIALITY.NS', 'SPAL.NS', 'SOMATEX.NS', 'SMLISUZU.NS', 'SIYSIL.NS', 'SPYL.NS', 'SREEL.NS', 'SINTEX.NS', 'AHLWEST.NS', 'SINTERCOM.NS', 'SSWL.NS', 'SGL.NS', 'SILGO.NS', 'AHLEAST.NS', 'SHRIPISTON.NS', 'STOVEKRAFT.NS', 'SHREERAMA.NS', 'SHOPERSTOP.NS', 'SHIVATEX.NS', 'SHIVAMILLS.NS', 'SHIVAMAUTO.NS', 'SHIL.NS', 'SUBROS.NS', 'SHARDAMOTR.NS', 'SUMEETINDS.NS', 'SUNCLAYLTD.NS', 'SIL.NS', 'ASAL.NS', 'RAYMOND.NS', 'RANEHOLDIN.NS', 'PCJEWELLER.NS', 'PATSPINLTD.NS', 'PAGEIND.NS', 'THOMASCOTT.NS', 'TIINDIA.NS', 'TIMETECHNO.NS', 'ORIENTLTD.NS', 'ORIENTHOT.NS', 'ORIENTELEC.NS', 'ORICONENT.NS', 'ORBTEXP.NS', 'OMAXAUTO.NS', 'OLECTRA.NS', 'ARCHIES.NS', 'TITAN.NS', 'TMRVL.NS', 'NRBBEARING.NS', 'TOKYOPLAST.NS', 'NITINSPIN.NS', 'NILKAMAL.NS', 'ARVIND.NS', 'TRENT.NS', 'ARVINDFASN.NS', 'NDRAUTO.NS', 'NDL.NS', 'SPLIL.NS', 'TTKPRESTIG.NS', 'ASAHIINDIA.NS', 'ARROWGREEN.NS', 'ADVANIHOTR.NS', 'PEARLPOLY.NS', 'PGIL.NS', 'RANEENGINE.NS', 'SUTLEJTEX.NS', 'SUULD.NS', 'SWANENERGY.NS', 'SWARAJENG.NS', 'RAJRAYON.NS', 'RAJESHEXPO.NS', 'SYMPHONY.NS', 'TAJGVK.NS', 'TALBROAUTO.NS', 'TATAMOTORS.NS', 'TATAMTRDVR.NS', 'ADL.NS', 'THOMASCOOK.NS', 'PRICOLLTD.NS', 'TCNSBRANDS.NS', 'PRECOT.NS', 'PRECAM.NS', 'TCPLPACK.NS', 'PRAXIS.NS', 'PRADIP.NS', 'PPAP.NS', 'TGBHOTELS.NS', 'APOLLOTYRE.NS', 'PIONEEREMB.NS', 'PILITA.NS', 'APOLSINHOT.NS', 'THANGAMAYL.NS', 'TBZ.NS', 'BUTTERFLY.NS', 'MITTAL.NS', 'HLVLTD.NS', 'GANECOS.NS', 'GARFIBRES.NS', 'DPABHUSHAN.NS', 'DONEAR.NS', 'DOLLAR.NS', 'HAVISHA.NS', 'GBGLOBAL.NS', 'BHARATGEAR.NS', 'GINNIFILA.NS', 'DYNAMATECH.NS', 'DELTACORP.NS', 'BOROLTD.NS', 'BORORENEW.NS', 'DCMNVL.NS', 'GNA.NS', 'FELDVR.NS', 'DAMODARIND.NS', 'BHARATFORG.NS', 'BOSCHLTD.NS', 'BHANDARI.NS', 'GLOBE.NS', 'EASEMYTRIP.NS', 'EASTSILK.NS', 'BIL.NS', 'FIEMIND.NS', 'EXIDEIND.NS', 'FILATEX.NS', 'BIRLATYRE.NS', 'EUROTEXIND.NS', 'BKMINDST.NS', 'FLEXITUFF.NS', 'EPL.NS', 'FLFL.NS', 'ENDURANCE.NS', 'EMMBI.NS', 'ELGIRUBCO.NS', 'FMGOETZE.NS', 'FORCEMOT.NS', 'FRETAIL.NS', 'EIHOTEL.NS', 'EIHAHOTELS.NS', 'HEROMOTOCO.NS', 'GRPLTD.NS', 'GABRIEL.NS', 'EICHERMOT.NS', 'HIMATSEIDE.NS', 'CROMPTON.NS', 'DANGEE.NS', 'HINDCOMPOS.NS', 'GOKEX.NS', 'CHALET.NS', 'CRAFTSMAN.NS', 'GOLDIAM.NS', 'GOODYEAR.NS', 'GREENLAM.NS', 'GREENPANEL.NS', 'CENTURYPLY.NS', 'BRFL.NS', 'CENTENKA.NS', 'CEATLTD.NS', 'CCHHL.NS', 'CASTEXTECH.NS', 'HITECHCORP.NS', 'HITECHGEAR.NS', 'CANTABIL.NS', 'BSL.NS', 'BYKE.NS', 'CELEBRITY.NS', 'COFFEEDAY.NS', 'GTNTEX.NS', 'FEL.NS', 'GOENKA.NS', 'COX&KINGS.NS', 'CORALFINAC.NS', 'HINDNATGLS.NS', 'COSMOFILMS.NS', 'HINDMOTORS.NS']
    
    cs = ['JAINSTUDIO.NS', 'JAGRAN.NS', 'RCOM.NS', 'INOXLEISUR.NS', 'ROUTE.NS', 'SABEVENTS.NS', 'SABTN.NS', 'INDUSTOWER.NS', 'SAMBHAAV.NS', 'SANDESH.NS', 'SAREGAMA.NS', 'NAUKRI.NS', 'INDIAMART.NS', 'MATRIMONY.NS', 'DNAMEDIA.NS', 'SHEMAROO.NS', 'DISHTV.NS', 'IMAGICAA.NS', 'IDEA.NS', 'HTMEDIA.NS', 'SILLYMONKS.NS', 'DGCONTENT.NS', 'SITINET.NS', 'ENIL.NS', 'SCHAND.NS', 'RAJTV.NS', 'EROSMEDIA.NS', 'NAVNETEDUL.NS', 'NAZARA.NS', 'NDTV.NS', 'NETWORK18.NS', 'NEXTMEDIA.NS', 'DEN.NS', 'BHARTIARTL.NS', 'NXTDIGITAL.NS', 'ONMOBILE.NS', 'GFLLIMITED.NS', 'GTL.NS', 'ORTEL.NS', 'GTPL.NS', 'PFOCUS.NS', 'PNC.NS', 'MUKTAARTS.NS', 'JUSTDIAL.NS', 'PRESSMN.NS', 'MTNL.NS', 'BALAJITELE.NS', 'HATHWAY.NS', 'MPSLTD.NS', 'BCG.NS', 'RADAAN.NS', 'RADIOCITY.NS', 'RAILTEL.NS', 'BAGFILMS.NS', 'PVR.NS', 'HMVL.NS', 'TV18BRDCST.NS', 'DALALSTCOM.NS', 'UFO.NS', 'CYBERMEDIA.NS', 'TIPSINDLTD.NS', 'DBCORP.NS', 'SUNTV.NS', 'TATACOMM.NS', 'TVVISION.NS', 'ZEEL.NS', 'TOUCHWOOD.NS', 'AFFLE.NS', 'TVTODAY.NS', 'ZEEMEDIA.NS', 'CINEVISTA.NS', 'VERTOZ.NS', 'CREATIVEYE.NS', 'TTML.NS']

    bm = ['ASIANPAINT.NS', 'ULTRACEMCO.NS', 'JSWSTEEL.NS', 'HINDZINC.NS', 'TATASTEEL.NS', 'VEDL.NS', 'SHREECEM.NS', 'PIDILITIND.NS', 'GRASIM.NS', 'HINDALCO.NS', 'BERGEPAINT.NS', 'AMBUJACEM.NS', 'UPL.NS', 'NMDC.NS', 'SAIL.NS', 'JINDALSTEL.NS', 'PIIND.NS', 'SRF.NS', 'ACC.NS', 'DALBHARAT.NS', 'KANSAINER.NS', 'AARTIIND.NS', 'BAYERCROP.NS', 'ATUL.NS', 'DEEPAKNTR.NS', 'COROMANDEL.NS', 'RAMCOCEM.NS', 'JKCEMENT.NS', 'TATACHEM.NS', 'VINATIORGA.NS', 'HINDCOPPER.NS', 'NAVINFLUOR.NS', 'SUMICHEM.NS', 'APLAPOLLO.NS', 'LINDEINDIA.NS', 'NATIONALUM.NS', 'CASTROLIND.NS', 'KIOCL.NS', 'INDIGOPNTS.NS', 'CHAMBLFERT.NS', 'SOLARINDS.NS', 'BASF.NS', 'TATASTLBSL.NS', 'DCMSHRIRAM.NS', 'GALAXYSURF.NS', 'AKZOINDIA.NS', 'FINEORG.NS', 'FLUOROCHEM.NS', 'RATNAMANI.NS', 'FACT.NS', 'BIRLACORPN.NS', 'BALAMINES.NS', 'ALKYLAMINE.NS', 'ANURAS.NS', 'ROSSARI.NS', 'PRSMJOHNSN.NS', 'PRINCEPIPE.NS', 'SUPPETRO.NS', 'GNFC.NS', 'RALLIS.NS', 'LXCHEM.NS', 'RAIN.NS', 'BHARATRAS.NS', 'CENTURYTEX.NS', 'INDIACEM.NS', 'HEIDELBERG.NS', 'ADVENZYMES.NS', 'VALIANTORG.NS', 'JKLAKSHMI.NS', 'GSFC.NS', 'SUDARSCHEM.NS', 'RCF.NS', 'JSL.NS', 'TATASTLLP.NS', 'RESPONIND.NS', 'MOIL.NS', 'DHANUKA.NS', 'STARCEMENT.NS', 'PRIVISCL.NS', 'JSLHISAR.NS', 'MIDHANI.NS', 'WELCORP.NS', 'GULFOILLUB.NS', 'PHILIPCARB.NS', 'MEGH.NS', 'JINDALPOLY.NS', 'POLYPLEX.NS', 'NFL.NS', 'GPIL.NS', 'NOCIL.NS', 'TATAMETALI.NS', 'GUJALKALI.NS', 'SHARDACROP.NS', 'HERANBA.NS', 'JSWISPL.NS', 'DEEPAKFERT.NS', 'JINDALSAW.NS', 'OAL.NS', 'BEPL.NS', 'ASTEC.NS', 'JKPAPER.NS', 'GREENPLY.NS', 'ORIENTCEM.NS', 'GHCL.NS', 'SURYAROSNI.NS', 'MAITHANALL.NS', 'INEOSSTYRO.NS', 'CAMLINFINE.NS', 'TINPLATE.NS', 'HSCL.NS', 'NEOGEN.NS', 'MAHSEAMLES.NS', 'SARDAEN.NS', 'SAGCEM.NS', 'TIDEWATER.NS', 'JAICORPLTD.NS', 'MUKANDLTD.NS', 'CHEMCON.NS', 'APCOTEXIND.NS', 'PRAKASH.NS', 'KIRIINDUS.NS', 'USHAMART.NS', 'KSL.NS', 'ORISSAMINE.NS', 'INDIAGLYCO.NS', 'GALLISPAT.NS', 'SOTL.NS', 'SUNFLAG.NS', 'IGPL.NS', 'PUNJABCHEM.NS', 'KCP.NS', 'MANALIPETC.NS', 'ELECTCAST.NS', 'EXCELINDUS.NS', 'ASHAPURMIN.NS', 'WSTCSTPAPR.NS', 'IFGLEXPOR.NS', 'KESORAMIND.NS', 'ESTER.NS', 'JAYNECOIND.NS', 'BODALCHEM.NS', 'SANGHIIND.NS', 'IMFA.NS', 'MANGCHEFER.NS', 'ANDHRSUGAR.NS', 'AARTISURF.NS', 'INSECTICID.NS', 'CLNINDIA.NS', 'FAIRCHEMOR.NS', 'KINGFA.NS', 'TIRUMALCHM.NS', 'SHREDIGCEM.NS', 'RAJRATAN.NS', 'NACLIND.NS', 'VIDHIING.NS', 'GOCLCORP.NS', 'SESHAPAPER.NS', 'TNPL.NS', 'OCCL.NS', 'SIRCA.NS', 'ANDHRAPAP.NS', 'FCL.NS', 'BHAGERIA.NS', 'FOSECOIND.NS', 'DCW.NS', 'NCLIND.NS', 'SPIC.NS', 'SATIA.NS', 'NATHBIOGEN.NS', 'AVTNPL.NS', 'TNPETRO.NS', 'VSSL.NS', 'MANGLMCEM.NS', 'SALASAR.NS', 'GULPOLY.NS', 'UNIENTER.NS', 'PLASTIBLEN.NS', 'DECCANCE.NS', 'BESTAGRO.NS', 'KUANTUM.NS', 'APCL.NS', 'DYNPRO.NS', 'KANORICHEM.NS', 'MANINDS.NS', 'JAIBALAJI.NS', 'ORIENTPPR.NS', 'JAYAGROGN.NS', 'SHREEPUSHK.NS', 'GALLANTT.NS', 'STEELXIND.NS', 'SHALPAINTS.NS', 'NAGAFERT.NS', 'SRHHYPOLTD.NS', 'JUBLINDS.NS', 'MADRASFERT.NS', 'ASAHISONG.NS', 'MSPL.NS', 'ZUARI.NS', 'KAMDHENU.NS', 'NRAIL.NS', 'HITECH.NS', 'VISHNU.NS', 'BHARATWIRE.NS', 'DICIND.NS', 'GSCLCEMENT.NS', 'CHEMBOND.NS', 'ORIENTABRA.NS', 'GOACARBON.NS', 'VINYLINDIA.NS', 'ISMTLTD.NS', 'MCL.NS', 'PODDARMENT.NS', 'RAMANEWS.NS', 'AKSHARCHEM.NS', 'MMP.NS', 'KOTHARIPET.NS', 'AGARIND.NS', 'PDMJEPAPER.NS', 'ARVEE.NS', 'KRISHANA.NS', 'CHEMFAB.NS', 'GENUSPAPER.NS', 'STARPAPER.NS', 'SHYAMCENT.NS', 'ASTRON.NS', 'KAKATCEM.NS', 'MBAPL.NS', 'ANDHRACEMT.NS', 'MANAKSTEEL.NS', 'BALLARPUR.NS', 'BHAGYANGR.NS', '20MICRONS.NS', 'PREMEXPLN.NS', 'BSHSL.NS', 'RUCHIRA.NS', 'JOCIL.NS', 'ARIES.NS', 'SEYAIND.NS', 'ADHUNIKIND.NS', 'MAHASTEEL.NS', 'MAANALU.NS', 'XPROINDIA.NS', 'RAMASTEEL.NS', 'SHREYANIND.NS', 'VISASTEEL.NS', 'UTTAMSTL.NS', 'IVP.NS', 'SHRENIK.NS', 'VIKASWSP.NS', 'RAJMET.NS', 'VIKASPROP.NS', 'SIGIND.NS', 'MANAKALUCO.NS', 'PREMIERPOL.NS', 'SICAGEN.NS', 'BEDMUTHA.NS', 'ABMINTLTD.NS', 'SAGARDEEP.NS', 'VIKASECO.NS', 'ARCHIDPLY.NS', 'SUPREMEENG.NS', 'TAINWALCHM.NS', 'HISARMETAL.NS', 'ALKALI.NS', 'SUNDARAM.NS', 'CENTEXT.NS', 'WIPL.NS', 'GAL.NS', 'MALUPAPER.NS', 'CUBEXTUB.NS', 'BVCL.NS', 'VASWANI.NS', 'SALSTEEL.NS', 'SANGINITA.NS', 'KRIDHANINF.NS', 'ROHITFERRO.NS', 'AGROPHOS.NS', 'NATNLSTEEL.NS', 'BURNPUR.NS', 'PRAKASHSTL.NS', 'SEPOWER.NS', 'MANGTIMBER.NS', 'ANKITMETAL.NS', 'MAGNUM.NS', 'ZENITHSTL.NS', 'JIYAECO.NS', 'IMPEXFERRO.NS', 'SMPL.NS', 'GFSTEELS.NS', 'NTL.NS', 'ARENTERP.NS']        
 
      
    # Title
    st.title("Nuggets!")
    # Subheader
    st.subheader("Smart way to invest money")
    # Diaplay Images
      
    # import Image from pillow to open images
    
    img = Image.open(r"C:/Users/Hp/nuggets/title.png")
    #img = Image.open(r"title.png")  
    st.image(img, width=200)
    total_portfolio_value = int(st.text_input("Amount to Invest", 0))
    sector_name = st.selectbox("Sector Wise Stocks: ",
                            ['Real Estate stock' , ' Industrail stocks',
                            'Healthcare stocks','Finance stocks',
                            'Energy stocks','Consumer defensive stocks',
                            'Consumer cyclical','Communication server stocks',' Utility stocks', 'Technology stocks ',])
    target_risk = 0.1
    diverse = itertools.chain(util_lc[:2],re_lc[:2], tech_lc[:2], eng_lc[:2], ind_lc[:2],cs_lc[:2],cd_lc[:2], cc_lc[:2],health_lc[:2], fs_lc[:2],bm_lc[:2])
    diverse = list(diverse)
    if(sector_name==' Utility stocks'):
        tickers = util_lc
    elif(sector_name=='Technology stocks '):
        tickers = tech_mc
    elif(sector_name=='Real Estate stock'):
        tickers = re_lc
    elif(sector_name==' Industrail stocks'):
        tickers = ind_mc
    elif(sector_name=='Healthcare stocks'):
        target_risk = 0.05        
        tickers = health_mc
    elif(sector_name=='Finance stocks'):
        tickers = fs_lc
    elif(sector_name=='Energy stocks'):
        tickers = eng_lc
    elif(sector_name=='Consumer defensive stocks'):
        tickers = cd_mc
    elif(sector_name=='Consumer cyclical'):
        tickers = cc_lc
    else:
        tickers = cs_sc
  
    
    if(st.button('Generate portfolio')):
        if(sector_name==' Utility stocks'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(util_mc,total_portfolio_value)
        elif(sector_name=='Technology stocks '):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name=='Real Estate stock'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name==' Industrail stocks'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(ind_lc,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name=='Healthcare stocks'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
            target_risk = 0.1
        elif(sector_name=='Finance stocks'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name=='Energy stocks'):
            hrp_optimization(eng_mc, total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name=='Consumer defensive stocks'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        elif(sector_name=='Consumer cyclical'):
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cvar_target_optimization(tickers, total_portfolio_value, target_risk)
            cla_optimization(tickers,total_portfolio_value)
            ga(tickers,total_portfolio_value)
        else:
            hrp_optimization(tickers, total_portfolio_value)
            ef_optimization(tickers,total_portfolio_value)
            cvar_optimization(tickers,total_portfolio_value)
            cla_optimization(tickers,total_portfolio_value)


def get_prices(tickers):
  try:
    ohlc = yf.download(tickers, period="max") 
  except:
    pass
  prices = ohlc["Adj Close"].dropna(how="all")
  return prices


def get_expected_returns(prices):
  returns = expected_returns.returns_from_prices(prices).dropna()
  return returns

def get_discreet_allocation(weights,prices,total_portfolio_value):
  latest_prices = prices.iloc[-1]  # prices as of the day you are allocating
  da = DiscreteAllocation(weights, latest_prices, total_portfolio_value, short_ratio=0.3)
  alloc, leftover = da.lp_portfolio()
  return alloc, leftover

def print_discreet_allocation(weights,prices, total_portfolio_value):
  da,leftover = get_discreet_allocation(weights,prices, total_portfolio_value)
  da=dict(da)
  for key in da:
        da[key] = int(da[key])
  temp="Discrete allocation performed with "+ str(round(leftover,2))+" leftover"
  st.write(temp)
  st.write(da)
  
def hrp_optimization(tickers,portfolio_value):
  prices = get_prices(tickers)
  returns = get_expected_returns(prices)
  hrp = HRPOpt(returns)
  hrp.optimize()
  weights = hrp.clean_weights()
  st.success("Portfolio 1 HRP (Hierarchial Risk Parity)")
  print_discreet_allocation(weights,prices,portfolio_value)
  num_small = len([k for k in weights if weights[k] <= 1e-4])
  call=num_small/len(hrp.tickers)
  temp= str(round(call,2))+" tickers have zero weight"
  st.write(temp)
  st.info("Portfolio Performance")
  performance = hrp.portfolio_performance(verbose=True)
  ann1="Expected annual return: "+ str(round(performance[0] * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(performance[1] * 100, 2)) + "%"
  ann3="Sharpe Ratio: "+str(round(performance[2], 2))
  st.write(ann1)
  st.write(ann2)
  st.write(ann3)
  
def get_mu(prices):
  mu = expected_returns.capm_return(prices)
  return mu

def get_S(prices):
  S = risk_models.semicovariance(prices)
  return S

def ef_optimization(tickers,total_portfolio_value):

  prices = get_prices(tickers)
  mu = get_mu(prices)
  S = get_S(prices)
  initial_weights = np.array([1/len(tickers)] * len(tickers))

  ef = EfficientFrontier(mu, S)
  ef.add_objective(objective_functions.transaction_cost, w_prev=initial_weights, k=0.001)
  ef.add_objective(objective_functions.L2_reg, gamma=0.05)  # default is 1
  ef.min_volatility()

  weights = ef.clean_weights()
  st.write("---------------------------------------------------------------")
  st.success("Portfolio 2 EF (Efficient Frontier)")
  print_discreet_allocation(weights,prices,total_portfolio_value)
  num_small = len([k for k in weights if weights[k] <= 1e-4])
  call=num_small/len(ef.tickers)
  temp=str(round(call,2))+" tickers have zero weight"
  st.write(temp)

  st.info("Portfolio Performance ")
  performance = ef.portfolio_performance(verbose=True)
  ann1="Expected annual return: "+ str(round(performance[0] * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(performance[1] * 100, 2)) + "%"
  ann3="Sharpe Ratio: "+str(round(performance[2], 2))
  st.write(ann1)
  st.write(ann2)
  st.write(ann3)

def cvar_optimization(tickers,total_portfolio_value):

  prices = get_prices(tickers)
  mu = get_mu(prices)
  returns = get_expected_returns(prices)
  ec = EfficientCVaR(mu, returns)
  ec.min_cvar()

  weights = ec.clean_weights()
  st.write("---------------------------------------------------------------")
  st.success("Portfolio 3 CVaR (Conditional Variable at Risk)")
  print_discreet_allocation(weights,prices,total_portfolio_value)
  num_small = len([k for k in weights if weights[k] <= 1e-4])
  call=num_small/len(ec.tickers)
  temp=str(round(call,2))+" tickers have zero weight"
  st.write(temp)
  st.info("Portfolio Performance ")
  performance = ec.portfolio_performance(verbose=True)
  ann1="Expected annual return: "+ str(round(performance[0] * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(performance[1] * 100, 2)) + "%"
  #ann3="Sharpe Ratio: "+str(round(performance[2], 2))
  st.write(ann1)
  st.write(ann2)
  #st.write(ann3)


def cvar_target_optimization(tickers,total_portfolio_value,target_risk):

  prices = get_prices(tickers)
  mu = get_mu(prices)
  returns = get_expected_returns(prices)
  ec = EfficientCVaR(mu, returns)
  ec.efficient_risk(target_cvar=target_risk)

  weights = ec.clean_weights()
  st.write("---------------------------------------------------------------")
  st.success("Portfolio 4 CVaR Target (Conditional Variable at Risk) ")
  print_discreet_allocation(weights,prices,total_portfolio_value)
  num_small = len([k for k in weights if weights[k] <= 1e-4])
  call=num_small/len(ec.tickers)
  temp=str(round(call,2))+" tickers have zero weight"
  st.write(temp)
  st.info("Portfolio Performance ")
  performance = ec.portfolio_performance(verbose=True)
  ann1="Expected annual return: "+ str(round(performance[0] * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(performance[1] * 100, 2)) + "%"
  #ann3="Sharpe Ratio: "+str(round(performance[2], 2))
  st.write(ann1)
  st.write(ann2)
  #st.write(ann3)

def cla_optimization(tickers,total_portfolio_value):

  prices = get_prices(tickers)
  mu = get_mu(prices)
  S = get_S(prices)

  cla = CLA(mu, S)
  cla.max_sharpe()

  weights = cla.clean_weights()
  st.write("---------------------------------------------------------------")
  st.success("Portfolio 5 CLA (Critical Line Algorithm)")
  print_discreet_allocation(weights,prices,total_portfolio_value)
  st.write("\n")

  num_small = len([k for k in weights if weights[k] <= 1e-4])
  call=num_small/len(cla.tickers)
  temp=str(round(call,2))+" tickers have zero weight"
  st.write(temp)

  st.info("Portfolio Performance ")
  performance = cla.portfolio_performance(verbose=True)
  ann1="Expected annual return: "+ str(round(performance[0] * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(performance[1] * 100, 2)) + "%"
  ann3="Sharpe Ratio: "+str(round(performance[2], 2))
  st.write(ann1)
  st.write(ann2)
  st.write(ann3)

def get_discreet_ga_allocation(weights,prices,total_portfolio_value):
  latest_prices = prices.iloc[-1]  # prices as of the day you are allocating
  da = DiscreteAllocation(weights, latest_prices, total_portfolio_value, short_ratio=0.3)
  alloc, leftover = da.lp_portfolio()
  return alloc

def get_data(tickers):
    portfolio = get_prices(tickers)
    returns = np.log(portfolio / portfolio.shift(1))
    
    port_return = np.array(returns.mean() * 252)
    port_risk = returns.cov()
  
    return portfolio, port_return, port_risk



def generate_weights(inputs, population):
    n_assets = len(inputs.columns)
    array = np.empty((population, (n_assets + 2)))
    weights = []
    
    for i in range(0, population):
        weighting = np.random.random(n_assets)
        weighting /= np.sum(weighting)
        weights.append(weighting)
    weights = np.array(weights)
    
    for i in range(0, n_assets):
       array[:, i] = weights[:, i]
       
    return array, n_assets



def fitness_func(weights, x1, x2, n_assets, riskFree):
    fitness = []
    
    for i in range(0, len(weights)):
        w_return = (weights[i, 0:n_assets] * x1) 
        w_risk = np.sqrt(np.dot(weights[i, 0:n_assets].T, np.dot(x2, weights[i, 0:n_assets]))) * np.sqrt(252)
        score = ((np.sum(w_return) * 100) - riskFree) / (np.sum(w_risk) * 100)
        fitness.append(score)
        
    fitness = np.array(fitness).reshape(len(weights))
    weights[:, n_assets] = fitness
    
    return weights



def elitism(elitism_rate, fit_func_res, n_assets):
    sorted_ff = fit_func_res[fit_func_res[:, n_assets].argsort()]
    elite_w = int(len(sorted_ff) * elitism_rate)
    elite_results = sorted_ff[-elite_w:]
    non_elite_results = sorted_ff[:-elite_w] 
    
    return elite_results, non_elite_results



def selection(parents, n_assets):     
    sol_len = int(len(parents) / 2)
    if (sol_len % 2) != 0: sol_len = sol_len + 1
    crossover_gen = np.empty((0, (n_assets + 2)))  
    
    for i in range(0, sol_len):
        parents[:, (n_assets + 1)] = np.cumsum(parents[:, n_assets]).reshape(len(parents))
        rand = random.randint(0, int(sum(parents[:, n_assets])))
        
        for i in range(0, len(parents)): nearest_val = min(parents[i:, (n_assets + 1)], key = lambda x: abs(x - rand))
        val = np.where(parents == nearest_val)
        index = val[0][0]
        
        next_gen = parents[index].reshape(1, (n_assets + 2))
        
        crossover_gen = np.append(crossover_gen, next_gen, axis = 0) 
        parents = np.delete(parents, (val[0]), 0)
        
    non_crossover_gen = crossover_gen.copy()
    
    return crossover_gen, non_crossover_gen



def crossover(probability, weights, assets):   
    for i in range(0, int((len(weights))/2), 2): 
        gen1, gen2 = weights[i], weights[i+1]
        gen1, gen2 = uni_co(gen1, gen2, assets, probability)
        weights[i], weights[i+1] = gen1, gen2
        
    weights = normalise(weights, assets)
    
    return weights
    


def uni_co(gen1, gen2, assets, crossover_rate):
    prob = np.random.normal(1, 1, assets)
    
    for i in range(0, len(prob)):
        if prob[i] > crossover_rate:
            gen1[i], gen2[i] = gen2[i], gen1[i]  
            
    return gen1, gen2



def mutation(probability, generation, assets): 
    weight_n = len(generation) * ((np.shape(generation)[1]) - 2)
    mutate_gens = int(weight_n * probability)
    
    if (mutate_gens >= 1):
        for i in range(0, mutate_gens):
            rand_pos_x, rand_pos_y = random.randint(0, (len(generation) - 1)), random.randint(0, (assets - 1))
            mu_gen = generation[rand_pos_x][rand_pos_y]
            mutated_ind = mu_gen * np.random.normal(0,1)
            generation[rand_pos_x][rand_pos_y] = abs(mutated_ind)
            generation = normalise(generation, assets)
        return generation
    else:
        return generation



def normalise(generation, assets):
    for i in range(0, len(generation)):
        generation[i][0:assets] /= np.sum(generation[i][0:assets])
    return generation



def next_gen(elites, children, no_cross_parents):
    weights = np.vstack((elites, children, no_cross_parents))
    return weights 



def optimal_solution(generations, assets):
    optimal_weights = generations[generations[:, (assets + 1)].argsort()]
    return optimal_weights[0]



def avg_gen_result(weights, n_assets):
    average = round(np.mean(weights[:, n_assets]), 2)
    return average



def genetic_algorithm(tickers, risk_free_rate, population, generations, crossover_rate, mutation_rate, elite_rate):
    weights, port_return, port_risk = get_data(tickers)
    weights, n_assets = generate_weights(weights, population)

    for i in range(0, generations):
        results = fitness_func(weights, port_return, port_risk, n_assets, risk_free_rate)
        
        elites, parents = elitism(elite_rate, results, n_assets)
        parents, no_cross_parents = selection(parents, n_assets)
        children = crossover(crossover_rate, parents, n_assets)
        children = mutation(mutation_rate, children, n_assets) 
        
        weights = next_gen(elites, children, no_cross_parents)
        
        avg_res = avg_gen_result(weights, n_assets)
        # print('Generation', i, ': Average Sharpe Ratio of', avg_res, 'from', len(weights), 'chromosomes')
        
    opt_solution = optimal_solution(weights, n_assets)
    
    return opt_solution



def ga(tickers,total_portfolio_value):

  population = 150
  risk_free_rate = 2
  generations = 40
  crossover_rate = 0.4
  mutation_rate = 0.01
  elite_rate = 0.25

# Run Function and Return Optimal Weights

  optimal_weights = genetic_algorithm(tickers, risk_free_rate, population, generations, crossover_rate, mutation_rate, elite_rate)

  optimal_weights_list = optimal_weights.tolist()
  ticker_weights_list = {}
  for i in range(len(tickers)):
    ticker_weights_list[tickers[i]] = optimal_weights_list[i]

  ticker_list = list(ticker_weights_list.keys())
  ohlc = yf.download(ticker_list, period="max")
  prices = ohlc["Adj Close"]

  alloc = get_discreet_ga_allocation(ticker_weights_list, prices,total_portfolio_value)
  alloc=dict(alloc)
  for key in alloc:
        alloc[key] = int(alloc[key])
  st.write("---------------------------------------------------------------")
  st.success("Portfolio 6 GA (Genetic Algorithm) ")
  st.write(alloc)


  mydict = ticker_weights_list
  mykeys = list(alloc.keys())
  newList={k:mydict[k] for k in mykeys if k in mydict}

  portfolio_weights = np.array(list(newList.values()))

  ohlc = yf.download(mykeys, period="max")
  portfolio = ohlc["Adj Close"]

  return_stocks = portfolio.pct_change()
  # return_stocks.tail(5)
  annual_returns = return_stocks.mean() * 252
  # annual_returns
  num_assets = len(mykeys)
  # num_assets
  weighted_returns = (portfolio_weights * return_stocks)
  # print(weighted_returns.tail())
  port_ret = weighted_returns.sum(axis=1)
  mean_ret = port_ret.mean()
  # mean_ret
  std_returns = port_ret.std()
  # std_returns
  cov_mat = return_stocks.cov()
  # cov_mat
  cov_mat_annual = cov_mat * 252
  port_returns_expected = np.sum(portfolio_weights * annual_returns)
  portfolio_volatility = np.sqrt(np.dot(portfolio_weights.T, np.dot(cov_mat_annual, portfolio_weights)))
  sr = mean_ret/std_returns
  ann1="Expected annual return: "+ str(round(port_returns_expected * 100, 2)) + "%"
  ann2="Annual volatility: "+ str(round(portfolio_volatility * 100, 2)) + "%"
  ann3="Sharpe Ratio: "+str(round(sr, 2))
  st.info("Portfolio Performance ")
  st.write(ann1)
  st.write(ann2)
  st.write(ann3)

  
